/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan;

import BLL.UserBLL;
import Entities.UserEntity;
import javax.swing.JOptionPane;


public class DangNhapFrame extends javax.swing.JFrame {

  UserBLL loginBL = new UserBLL();

  /**
   * Creates new form DangNhapFrame
   */
  public DangNhapFrame() {
    initComponents();
    setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pn_DangNhap = new javax.swing.JPanel();
    lb_DangNhap_Username = new javax.swing.JLabel();
    lb_DangNhap_Password = new javax.swing.JLabel();
    btn_DangNhap_DangNhap = new javax.swing.JButton();
    tf_DangNhap_Username = new javax.swing.JTextField();
    pf_Password = new javax.swing.JPasswordField();
    lb_DangNhap = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setBackground(new java.awt.Color(255, 255, 255));
    setResizable(false);

    pn_DangNhap.setBackground(new java.awt.Color(255, 255, 255));

    lb_DangNhap_Username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    lb_DangNhap_Username.setText("Tên Đăng Nhập:");

    lb_DangNhap_Password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    lb_DangNhap_Password.setText("Mật Khẩu:");

    btn_DangNhap_DangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login.png"))); // NOI18N
    btn_DangNhap_DangNhap.setText("Đăng Nhập");
    btn_DangNhap_DangNhap.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_DangNhap_DangNhapActionPerformed(evt);
      }
    });

    pf_Password.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        pf_PasswordActionPerformed(evt);
      }
    });

    lb_DangNhap.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    lb_DangNhap.setText("ĐĂNG NHẬP");

    javax.swing.GroupLayout pn_DangNhapLayout = new javax.swing.GroupLayout(pn_DangNhap);
    pn_DangNhap.setLayout(pn_DangNhapLayout);
    pn_DangNhapLayout.setHorizontalGroup(
      pn_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pn_DangNhapLayout.createSequentialGroup()
        .addGroup(pn_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(pn_DangNhapLayout.createSequentialGroup()
            .addGap(124, 124, 124)
            .addComponent(lb_DangNhap))
          .addGroup(pn_DangNhapLayout.createSequentialGroup()
            .addGap(37, 37, 37)
            .addGroup(pn_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(pn_DangNhapLayout.createSequentialGroup()
                .addComponent(lb_DangNhap_Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pf_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(pn_DangNhapLayout.createSequentialGroup()
                .addComponent(lb_DangNhap_Username)
                .addGap(46, 46, 46)
                .addComponent(tf_DangNhap_Username, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))))
        .addGap(48, 48, 48))
      .addGroup(pn_DangNhapLayout.createSequentialGroup()
        .addGap(136, 136, 136)
        .addComponent(btn_DangNhap_DangNhap)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    pn_DangNhapLayout.setVerticalGroup(
      pn_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pn_DangNhapLayout.createSequentialGroup()
        .addGap(34, 34, 34)
        .addComponent(lb_DangNhap)
        .addGap(36, 36, 36)
        .addGroup(pn_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lb_DangNhap_Username)
          .addComponent(tf_DangNhap_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(33, 33, 33)
        .addGroup(pn_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(pf_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lb_DangNhap_Password))
        .addGap(35, 35, 35)
        .addComponent(btn_DangNhap_DangNhap)
        .addContainerGap(47, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pn_DangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pn_DangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btn_DangNhap_DangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangNhap_DangNhapActionPerformed
      // TODO add your handling code here:
      UserEntity user = new UserEntity();
      user.setUsername(tf_DangNhap_Username.getText());
      user.setPassword(pf_Password.getText());
      int loginType = loginBL.getLogin(user.getUsername(), user.getPassword());
      String fullname = loginBL.getUser(tf_DangNhap_Username.getText(), String.valueOf(pf_Password.getPassword())).getFullName();
      switch (loginType) {
        case 1:
          user.setUserType("NhanVien");
          NhanVienFrame nhanVienFrame = new NhanVienFrame(fullname);
          nhanVienFrame.setVisible(true);
          nhanVienFrame.setExtendedState(nhanVienFrame.MAXIMIZED_BOTH);
          nhanVienFrame.setResizable(true);
          this.setVisible(false);

          break;
        case 2:
          user.setUserType("TruongNha");
          TruongNhaFrame truongNhaFrame = new TruongNhaFrame();
          truongNhaFrame.setVisible(true);
          truongNhaFrame.setExtendedState(truongNhaFrame.MAXIMIZED_BOTH);
          truongNhaFrame.setResizable(true);
          this.setVisible(false);
          break;
        default:
          JOptionPane.showMessageDialog(this, "Tên đăng nhập hoặc mật khẩu không chính xác.");
      }
    }//GEN-LAST:event_btn_DangNhap_DangNhapActionPerformed

  private void pf_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_PasswordActionPerformed
    // TODO add your handling code here:
    UserEntity user = new UserEntity();
    user.setUsername(tf_DangNhap_Username.getText());
    user.setPassword(pf_Password.getText());
    int loginType = loginBL.getLogin(user.getUsername(), user.getPassword());
    String fullname = loginBL.getUser(tf_DangNhap_Username.getText(), String.valueOf(pf_Password.getPassword())).getFullName();
    switch (loginType) {
      case 1:
        user.setUserType("NhanVien");
        NhanVienFrame nhanVienFrame = new NhanVienFrame(fullname);
        nhanVienFrame.setVisible(true);
        nhanVienFrame.setExtendedState(nhanVienFrame.MAXIMIZED_BOTH);
        nhanVienFrame.setResizable(true);
        this.setVisible(false);

        break;
      case 2:
        user.setUserType("TruongNha");
        TruongNhaFrame truongNhaFrame = new TruongNhaFrame();
        truongNhaFrame.setVisible(true);
        truongNhaFrame.setExtendedState(truongNhaFrame.MAXIMIZED_BOTH);
        truongNhaFrame.setResizable(true);
        this.setVisible(false);
        break;
      default:
        JOptionPane.showMessageDialog(this, "Tên đăng nhập hoặc mật khẩu không chính xác.");
    }
  }//GEN-LAST:event_pf_PasswordActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Windows".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(DangNhapFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(DangNhapFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(DangNhapFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(DangNhapFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new DangNhapFrame().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_DangNhap_DangNhap;
  private javax.swing.JLabel lb_DangNhap;
  private javax.swing.JLabel lb_DangNhap_Password;
  private javax.swing.JLabel lb_DangNhap_Username;
  private javax.swing.JPasswordField pf_Password;
  private javax.swing.JPanel pn_DangNhap;
  private javax.swing.JTextField tf_DangNhap_Username;
  // End of variables declaration//GEN-END:variables
}
