/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan;

import BLL.UserBLL;
import javax.swing.JOptionPane;

public class DoiMatKhauFrame extends javax.swing.JFrame {

    /**
     * Creates new form DoiMatKhauFrame
     */
    public DoiMatKhauFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pn_DoiMatKhau = new javax.swing.JPanel();
    lb_DoiMatKhau = new javax.swing.JLabel();
    lb_TenDangNhap = new javax.swing.JLabel();
    lb_MatKhauCu = new javax.swing.JLabel();
    lb_MatKhauMoi = new javax.swing.JLabel();
    lb_XacNhanMatKhau = new javax.swing.JLabel();
    btn_XacNhan = new javax.swing.JButton();
    btn_Huy = new javax.swing.JButton();
    tf_TenDangNhap = new javax.swing.JTextField();
    pf_MatKhauCu = new javax.swing.JPasswordField();
    pf_MatKhauMoi = new javax.swing.JPasswordField();
    pf_XacNhanMatKhau = new javax.swing.JPasswordField();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setBackground(new java.awt.Color(255, 255, 255));
    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    setResizable(false);

    pn_DoiMatKhau.setBackground(new java.awt.Color(255, 255, 255));

    lb_DoiMatKhau.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    lb_DoiMatKhau.setText("ĐỔI MẬT KHẨU");

    lb_TenDangNhap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    lb_TenDangNhap.setText("Tên Đăng Nhập:");

    lb_MatKhauCu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    lb_MatKhauCu.setText("Mật Khẩu Cũ:");

    lb_MatKhauMoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    lb_MatKhauMoi.setText("Mật Khẩu Mới:");

    lb_XacNhanMatKhau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    lb_XacNhanMatKhau.setText("Xác Nhận Mật Khẩu:");

    btn_XacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checked.png"))); // NOI18N
    btn_XacNhan.setText("Xác Nhận");
    btn_XacNhan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_XacNhanActionPerformed(evt);
      }
    });

    btn_Huy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/unchecked.png"))); // NOI18N
    btn_Huy.setText("Hủy");
    btn_Huy.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_HuyActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout pn_DoiMatKhauLayout = new javax.swing.GroupLayout(pn_DoiMatKhau);
    pn_DoiMatKhau.setLayout(pn_DoiMatKhauLayout);
    pn_DoiMatKhauLayout.setHorizontalGroup(
      pn_DoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_DoiMatKhauLayout.createSequentialGroup()
        .addContainerGap(51, Short.MAX_VALUE)
        .addGroup(pn_DoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lb_MatKhauCu)
          .addComponent(lb_MatKhauMoi)
          .addComponent(lb_XacNhanMatKhau)
          .addComponent(lb_TenDangNhap))
        .addGap(41, 41, 41)
        .addGroup(pn_DoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(tf_TenDangNhap)
          .addComponent(pf_MatKhauCu)
          .addComponent(pf_MatKhauMoi)
          .addComponent(pf_XacNhanMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(49, 49, 49))
      .addGroup(pn_DoiMatKhauLayout.createSequentialGroup()
        .addGap(79, 79, 79)
        .addComponent(btn_XacNhan)
        .addGap(41, 41, 41)
        .addComponent(btn_Huy)
        .addGap(0, 0, Short.MAX_VALUE))
      .addGroup(pn_DoiMatKhauLayout.createSequentialGroup()
        .addGap(122, 122, 122)
        .addComponent(lb_DoiMatKhau)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pn_DoiMatKhauLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_Huy, btn_XacNhan});

    pn_DoiMatKhauLayout.setVerticalGroup(
      pn_DoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pn_DoiMatKhauLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lb_DoiMatKhau)
        .addGap(33, 33, 33)
        .addGroup(pn_DoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(pn_DoiMatKhauLayout.createSequentialGroup()
            .addGroup(pn_DoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(pn_DoiMatKhauLayout.createSequentialGroup()
                .addGroup(pn_DoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(lb_TenDangNhap)
                  .addComponent(tf_TenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lb_MatKhauCu))
              .addComponent(pf_MatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(lb_MatKhauMoi))
          .addComponent(pf_MatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(pn_DoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(lb_XacNhanMatKhau)
          .addComponent(pf_XacNhanMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(35, 35, 35)
        .addGroup(pn_DoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btn_XacNhan)
          .addComponent(btn_Huy))
        .addContainerGap(61, Short.MAX_VALUE))
    );

    pn_DoiMatKhauLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_Huy, btn_XacNhan});

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pn_DoiMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pn_DoiMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btn_XacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XacNhanActionPerformed
        // TODO add your handling code here:
        UserBLL userBLL = new UserBLL();

        String tenDangNhap = tf_TenDangNhap.getText().trim();
        String matKhauCu = String.valueOf(pf_MatKhauCu.getPassword());
        String matKhauMoi = String.valueOf(pf_MatKhauMoi.getPassword());
        
        if(tf_TenDangNhap.getText().equals("") || String.valueOf(pf_MatKhauCu.getPassword()).equals("") || String.valueOf(pf_MatKhauMoi.getPassword()).equals("") || String.valueOf(pf_XacNhanMatKhau.getPassword()).equals(""))
        {
            JOptionPane.showMessageDialog(this, "Không được để trống thông tin");
            return;
        }       
        if(!String.valueOf(pf_MatKhauMoi.getPassword()).equals(String.valueOf(pf_XacNhanMatKhau.getPassword())))
        {
            JOptionPane.showMessageDialog(this, "Mật khẩu mới vừa nhập không trùng khớp với mật khẩu xác nhận.");
            return;
        }

        if(userBLL.getLogin(tenDangNhap, matKhauCu) != 1 && userBLL.getLogin(tenDangNhap, matKhauCu) != 2)
        {
            JOptionPane.showMessageDialog(this, "Tên đăng nhập hoặc mật khẩu cũ không chính xác.");
            return;
        }
        userBLL.Update(tenDangNhap, matKhauMoi);
        JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công");
    }//GEN-LAST:event_btn_XacNhanActionPerformed

    private void btn_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuyActionPerformed
        // TODO add your handling code here:
        tf_TenDangNhap.setText("");
        pf_MatKhauCu.setText("");
        pf_MatKhauMoi.setText("");
        pf_XacNhanMatKhau.setText("");
    }//GEN-LAST:event_btn_HuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoiMatKhauFrame().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_Huy;
  private javax.swing.JButton btn_XacNhan;
  private javax.swing.JLabel lb_DoiMatKhau;
  private javax.swing.JLabel lb_MatKhauCu;
  private javax.swing.JLabel lb_MatKhauMoi;
  private javax.swing.JLabel lb_TenDangNhap;
  private javax.swing.JLabel lb_XacNhanMatKhau;
  private javax.swing.JPasswordField pf_MatKhauCu;
  private javax.swing.JPasswordField pf_MatKhauMoi;
  private javax.swing.JPasswordField pf_XacNhanMatKhau;
  private javax.swing.JPanel pn_DoiMatKhau;
  private javax.swing.JTextField tf_TenDangNhap;
  // End of variables declaration//GEN-END:variables
}
