/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan;

import BLL.GhiNhanDienNuocBLL;
import BLL.LoaiNhaBLL;
import BLL.NhaBLL;
import BLL.PhongBLL;
import BLL.QuyDinhThoiGianBLL;
import BLL.ThuPhiDienNuocBLL;
import BLL.ThuPhiNoiTruBLL;
import BLL.XepPhongBLL;
import Entities.QuyDinhThoiGianEntity;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;


public class KhoiNhaFrame extends javax.swing.JFrame {

    /**
     * Creates new form KhoiNhaFrame
     */
    public KhoiNhaFrame() {
        initComponents();
        ShowTable();
        showComboBoxGioiTinh();
        showComboBoxSoNguoi();
    }

    private void ShowTable() {
        Vector cols = new Vector();
        Vector data = new Vector();
        NhaBLL nhaBLL = new NhaBLL();

        nhaBLL.ShowTable(cols, data);
        tb_Nha.setModel(new AbstractTableModel() {
            @Override
            public int getRowCount() {
                return data.size();
            }

            @Override
            public int getColumnCount() {
                return cols.size();
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                Vector rowData = (Vector) (data.elementAt(rowIndex));
                return rowData.elementAt(columnIndex);
            }

            @Override
            public String getColumnName(int column) {
                return (String) cols.elementAt(column);
            }
        });
    }

    private void showComboBoxGioiTinh() {
        LoaiNhaBLL loaiNhaBLL = new LoaiNhaBLL();
        ArrayList<String> danhsachGioiTinh = loaiNhaBLL.LayGioiTinh();
        for (int i = 0; i < danhsachGioiTinh.size(); i++) {
            cb_GioiTinh.addItem(danhsachGioiTinh.get(i));
        }
    }

    private void showComboBoxSoNguoi() {
        LoaiNhaBLL loaiNhaBLL = new LoaiNhaBLL();
        ArrayList<Integer> danhSachSoNguoi = loaiNhaBLL.LaySoNguoi();
        for (int i = 0; i < danhSachSoNguoi.size(); i++) {
            cb_SoNguoi.addItem(String.valueOf(danhSachSoNguoi.get(i)));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pn_Nha = new javax.swing.JPanel();
    lb_KhoiNha = new javax.swing.JLabel();
    pn_Nha_ThongTin = new javax.swing.JPanel();
    lb_Nha = new javax.swing.JLabel();
    tf_Nha = new javax.swing.JTextField();
    lb_SoNguoi = new javax.swing.JLabel();
    cb_SoNguoi = new javax.swing.JComboBox<>();
    cb_GioiTinh = new javax.swing.JComboBox<>();
    lb_GioiTinh = new javax.swing.JLabel();
    btn_Them = new javax.swing.JButton();
    btn_Xoa = new javax.swing.JButton();
    btn_Sua = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tb_Nha = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setResizable(false);

    pn_Nha.setBackground(new java.awt.Color(255, 255, 255));

    lb_KhoiNha.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    lb_KhoiNha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/apartments.png"))); // NOI18N
    lb_KhoiNha.setText("KHỐI NHÀ");

    pn_Nha_ThongTin.setBackground(new java.awt.Color(255, 255, 255));
    pn_Nha_ThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Nhà"));

    lb_Nha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    lb_Nha.setText("Khối Nhà:");

    lb_SoNguoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    lb_SoNguoi.setText("Số Người:");

    lb_GioiTinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    lb_GioiTinh.setText("Giới Tính:");

    javax.swing.GroupLayout pn_Nha_ThongTinLayout = new javax.swing.GroupLayout(pn_Nha_ThongTin);
    pn_Nha_ThongTin.setLayout(pn_Nha_ThongTinLayout);
    pn_Nha_ThongTinLayout.setHorizontalGroup(
      pn_Nha_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pn_Nha_ThongTinLayout.createSequentialGroup()
        .addGap(28, 28, 28)
        .addGroup(pn_Nha_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lb_Nha)
          .addComponent(lb_SoNguoi)
          .addComponent(lb_GioiTinh))
        .addGap(29, 29, 29)
        .addGroup(pn_Nha_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(tf_Nha)
          .addComponent(cb_SoNguoi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cb_GioiTinh, 0, 137, Short.MAX_VALUE))
        .addContainerGap(52, Short.MAX_VALUE))
    );
    pn_Nha_ThongTinLayout.setVerticalGroup(
      pn_Nha_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pn_Nha_ThongTinLayout.createSequentialGroup()
        .addGroup(pn_Nha_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(tf_Nha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lb_Nha))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(pn_Nha_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lb_SoNguoi)
          .addComponent(cb_SoNguoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(pn_Nha_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cb_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lb_GioiTinh))
        .addGap(0, 11, Short.MAX_VALUE))
    );

    btn_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checked.png"))); // NOI18N
    btn_Them.setText("Thêm");
    btn_Them.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_ThemActionPerformed(evt);
      }
    });

    btn_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/unchecked.png"))); // NOI18N
    btn_Xoa.setText("Xóa");
    btn_Xoa.setToolTipText("");
    btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_XoaActionPerformed(evt);
      }
    });

    btn_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Refresh-icon.png"))); // NOI18N
    btn_Sua.setText("Sửa");
    btn_Sua.setToolTipText("");
    btn_Sua.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_SuaActionPerformed(evt);
      }
    });

    tb_Nha.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    tb_Nha.getTableHeader().setReorderingAllowed(false);
    tb_Nha.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tb_NhaMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tb_Nha);

    javax.swing.GroupLayout pn_NhaLayout = new javax.swing.GroupLayout(pn_Nha);
    pn_Nha.setLayout(pn_NhaLayout);
    pn_NhaLayout.setHorizontalGroup(
      pn_NhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pn_NhaLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btn_Them)
        .addGap(18, 18, 18)
        .addComponent(btn_Xoa)
        .addGap(26, 26, 26)
        .addComponent(btn_Sua)
        .addContainerGap())
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_NhaLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(lb_KhoiNha)
        .addGap(223, 223, 223))
      .addGroup(pn_NhaLayout.createSequentialGroup()
        .addGap(131, 131, 131)
        .addComponent(pn_Nha_ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(160, Short.MAX_VALUE))
      .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
    );

    pn_NhaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_Sua, btn_Them, btn_Xoa});

    pn_NhaLayout.setVerticalGroup(
      pn_NhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pn_NhaLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lb_KhoiNha)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(pn_Nha_ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
        .addGroup(pn_NhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btn_Them)
          .addComponent(btn_Xoa)
          .addComponent(btn_Sua))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pn_NhaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_Sua, btn_Them, btn_Xoa});

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(pn_Nha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(pn_Nha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        NhaBLL nhaBLL = new NhaBLL();
        LoaiNhaBLL loaiNhaBLL = new LoaiNhaBLL();

        if (tf_Nha.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên nhà.");
            return;
        }

        if (cb_GioiTinh.getSelectedItem().toString().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn giới tính.");
            return;
        }

        if (cb_SoNguoi.getSelectedItem().toString().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn số người.");
            return;
        }

        int maLoaiNha = loaiNhaBLL.LayMaLoaiNha(Integer.parseInt(cb_SoNguoi.getSelectedItem().toString().trim()), cb_GioiTinh.getSelectedItem().toString().trim());
        String tenNha = tf_Nha.getText().trim();

        if (nhaBLL.TimNha(tenNha)) {
            JOptionPane.showMessageDialog(this, "Không thể thêm. Tên nhà đã có trong danh sách.");
            return;
        }
        nhaBLL.Insert(tenNha, maLoaiNha);
        JOptionPane.showMessageDialog(this, "Thêm Nhà thành công.");
        ShowTable();

    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:

        NhaBLL nhaBLL = new NhaBLL();
        PhongBLL phongBLL = new PhongBLL();
        XepPhongBLL xepPhongBLL = new XepPhongBLL();
        ThuPhiNoiTruBLL thuPhiNoiTruBLL = new ThuPhiNoiTruBLL();
        GhiNhanDienNuocBLL ghiNhanDienNuocBLL = new GhiNhanDienNuocBLL();
        ThuPhiDienNuocBLL thuPhiDienNuocBLL = new ThuPhiDienNuocBLL();
        QuyDinhThoiGianBLL quyDinhThoiGianBLL = new QuyDinhThoiGianBLL();
        QuyDinhThoiGianEntity quyDinhThoiGianEntity = quyDinhThoiGianBLL.LayThoiGian();

        String tenNha = tf_Nha.getText().trim();
        int maNha = nhaBLL.LayMaNha(tenNha);

        if (tf_Nha.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên nhà hoặc chọn nhà ở bảng phía dưới.");
            return;
        }

        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa nhà " + tenNha + " khỏi danh sách?");
        if (choice == JOptionPane.YES_OPTION) {
            if (nhaBLL.TimNha(tenNha) == false) {
                JOptionPane.showMessageDialog(this, "Không thế xóa.\nNhà này không có trong danh sách.");
                return;
            }

            if (xepPhongBLL.KiemTraXepPhong(maNha, quyDinhThoiGianEntity.getNamHoc())) {
                JOptionPane.showMessageDialog(this, "Không thể xóa.\n Nhà này đang được sử dụng trong năm học hiện tại.");
                return;
            }
            thuPhiNoiTruBLL.delete(quyDinhThoiGianEntity.getNamHoc());
            xepPhongBLL.Delete(maNha);
            ghiNhanDienNuocBLL.Delete(maNha);
            thuPhiDienNuocBLL.Delete(maNha);
            phongBLL.Delete(maNha);
            nhaBLL.Delete(tenNha);
            ShowTable();
            JOptionPane.showMessageDialog(this, "Xóa thành công " + tenNha + " khỏi danh sách");
        }

    }//GEN-LAST:event_btn_XoaActionPerformed

    private void tb_NhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_NhaMouseClicked
        // TODO add your handling code here:
        int index = tb_Nha.getSelectedRow();
        tf_Nha.setText((String) tb_Nha.getValueAt(index, 1));
        cb_SoNguoi.setSelectedItem(String.valueOf(tb_Nha.getValueAt(index, 2)));
        cb_GioiTinh.setSelectedItem(tb_Nha.getValueAt(index, 3));

    }//GEN-LAST:event_tb_NhaMouseClicked

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:

        NhaBLL nhaBLL = new NhaBLL();
        QuyDinhThoiGianBLL quyDinhThoiGianBLL = new QuyDinhThoiGianBLL();
        QuyDinhThoiGianEntity quyDinhThoiGianEntity = quyDinhThoiGianBLL.LayThoiGian();
        XepPhongBLL xepPhongBLL = new XepPhongBLL();
        LoaiNhaBLL loaiNhaBLL = new LoaiNhaBLL();

        String tenNha = tf_Nha.getText().trim();
        String gioiTinh = cb_GioiTinh.getSelectedItem().toString().trim();
        int soNguoi = Integer.parseInt(cb_SoNguoi.getSelectedItem().toString().trim());
        int maLoaiNha = loaiNhaBLL.LayMaLoaiNha(soNguoi, gioiTinh);

        if (!tb_Nha.isColumnSelected(1) && !tb_Nha.isColumnSelected(2) && !tb_Nha.isColumnSelected(0)) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhà ở bảng phía dưới sau đó cập nhật lại thông tin ở trên.");
            return;
        }

        if (tf_Nha.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên nhà.");
            return;
        }

        if (cb_GioiTinh.getSelectedItem().toString().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn giới tính.");
            return;
        }

        if (cb_SoNguoi.getSelectedItem().toString().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn số người.");
            return;
        }

        int index = tb_Nha.getSelectedRow();
        int maNha = (int) tb_Nha.getValueAt(index, 0);

        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn thay đổi thông tin nhà được chọn?");
        if (choice == JOptionPane.YES_OPTION) {

            if (xepPhongBLL.KiemTraXepPhong(maNha, quyDinhThoiGianEntity.getNamHoc())) {
                JOptionPane.showMessageDialog(this, "Không thể sửa .\n Nhà này đang được sử dụng trong năm học hiện tại.");
                return;
            }
            nhaBLL.Update(tenNha, maNha, maLoaiNha);
            ShowTable();
            JOptionPane.showMessageDialog(this, "Cập nhật thành công.");
        }


    }//GEN-LAST:event_btn_SuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhoiNhaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhoiNhaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhoiNhaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhoiNhaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhoiNhaFrame().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_Sua;
  private javax.swing.JButton btn_Them;
  private javax.swing.JButton btn_Xoa;
  private javax.swing.JComboBox<String> cb_GioiTinh;
  private javax.swing.JComboBox<String> cb_SoNguoi;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lb_GioiTinh;
  private javax.swing.JLabel lb_KhoiNha;
  private javax.swing.JLabel lb_Nha;
  private javax.swing.JLabel lb_SoNguoi;
  private javax.swing.JPanel pn_Nha;
  private javax.swing.JPanel pn_Nha_ThongTin;
  private javax.swing.JTable tb_Nha;
  private javax.swing.JTextField tf_Nha;
  // End of variables declaration//GEN-END:variables
}
