/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan;

import BLL.GhiNhanDienNuocBLL;
import BLL.NhaBLL;
import BLL.PhongBLL;
import BLL.SinhVienBLL;
import BLL.TinhBLL;
import BLL.TruongBLL;
import Entities.SinhVienEntity;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;


public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        //setLocationRelativeTo(null);
        initComponents();
        ShowCombobox_Tinh();
        showComboBoxNha_TraCuuPhong();
        ShowComboBoxTruong_CapNhatThongTinSV();
        showComboBoxNha(cb_TraCuuDienNuoc_Nha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_TraCuu = new javax.swing.JTabbedPane();
        scrollPanel_CapNhat = new javax.swing.JScrollPane();
        pn_CapNhatThongTinSinhVien = new javax.swing.JPanel();
        lb_CapNhatThongTinSV_HoSoSV = new javax.swing.JLabel();
        pn_CapNhatThongTinSV_ThongTin = new javax.swing.JPanel();
        lb_CapNhatThongTinSV_HoSinhVien = new javax.swing.JLabel();
        tf_CapNhatThongTinSV_ThongTin_HoSinhVien = new javax.swing.JTextField();
        lb_CapNhatThongTinSV_ThongTin_TenSV = new javax.swing.JLabel();
        tf_CapNhatThongTinSV_ThongTin_TenSV = new javax.swing.JTextField();
        lb_CapNhatThongTinSV_ThongTin_CMND = new javax.swing.JLabel();
        lb_CapNhatThongTinSV_ThongTin_NgaySinh = new javax.swing.JLabel();
        lb_CapNhatThongTinSV_ThongTin_GioiTinh = new javax.swing.JLabel();
        lb_CapNhatThongTinSV_ThongTin_NgayCap = new javax.swing.JLabel();
        lb_CapNhatThongTinSV_ThongTin_MSSV = new javax.swing.JLabel();
        lb_CapNhatThongTinSV_ThongTin_Truong = new javax.swing.JLabel();
        btn_CapNhatThongTinSV_ThongTin_Luu = new javax.swing.JButton();
        btn_CapNhatThongTinSV_ThongTin_Huy = new javax.swing.JButton();
        dateChooser_CapNhatThongTinSV_ThongTin_NgaySinh = new com.toedter.calendar.JDateChooser();
        dateChooser_CapNhatThongTinSV_ThongTin_NgayCap = new com.toedter.calendar.JDateChooser();
        lb_CapNhatThongTinSV_ThongTin_Tinh = new javax.swing.JLabel();
        cb_CapNhatThongTinSV_ThongTin_Tinh = new javax.swing.JComboBox<>();
        lb_CapNhatThongTinSV_ThongTin_TonGiao = new javax.swing.JLabel();
        lb_CapNhatThongTinSV_ThongTin_QuocTich = new javax.swing.JLabel();
        lb_CapNhatThongTinSV_ThongTin_DanToc = new javax.swing.JLabel();
        tf_CapNhatThongTinSV_ThongTin_DanToc = new javax.swing.JTextField();
        tf_CapNhatThongTinSV_ThongTin_QuocTich = new javax.swing.JTextField();
        tf_CapNhatThongTinSV_ThongTin_TonGiao = new javax.swing.JTextField();
        lb_CapNhatThongTinSV_ThongTin_SDT = new javax.swing.JLabel();
        lb_CapNhatThongTinSV_ThongTin_DiaChiNha = new javax.swing.JLabel();
        tf_CapNhatThongTinSV_ThongTin_SDT = new javax.swing.JTextField();
        tf_CapNhatThongTinSV_ThongTin_DiaChiNha = new javax.swing.JTextField();
        tf_CapNhatThongTinSV_CMND = new javax.swing.JTextField();
        tf_CapNhatThongTinSV_MSSV = new javax.swing.JTextField();
        tf_CapNhatThongTinSV_GioiTinh = new javax.swing.JTextField();
        cb_CapNhatThongTinSV_Truong = new javax.swing.JComboBox<>();
        tf_CapNhatThongTinSV_MaKTX = new javax.swing.JTextField();
        btn_CapNhatThongTinSV_Search = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb_CapNhatThongTinSV = new javax.swing.JTable();
        lb_CapNhatThongTinSV_MaKTX = new javax.swing.JLabel();
        scrollPanel_TraCuuSV = new javax.swing.JScrollPane();
        pn_TraCuuSV = new javax.swing.JPanel();
        lb_TraCuuSV_TabTraCuuSV = new javax.swing.JLabel();
        tf_TraCuuSV_TabTraCuuSV = new javax.swing.JTextField();
        btn_Search_TabTraCuuSV = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_TraCuuSV_TabTraCuuSV = new javax.swing.JTable();
        scrollPanel_TraCuuPhong = new javax.swing.JScrollPane();
        pn_TraCuuPhong = new javax.swing.JPanel();
        lb_TraCuuPhong = new javax.swing.JLabel();
        lb_TraCuuPhong_Nha = new javax.swing.JLabel();
        cb_TraCuuPhong_Nha = new javax.swing.JComboBox<>();
        lb_TraCuuPhong_Phong = new javax.swing.JLabel();
        cb_TraCuuPhong_Phong = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_TraCuuPhong = new javax.swing.JTable();
        scrollPanel_TraCuuDienNuoc = new javax.swing.JScrollPane();
        pn_TraCuuDienNuoc = new javax.swing.JPanel();
        lb_TraCuuDienNuoc = new javax.swing.JLabel();
        pn_TraCuuDienNuoc_ThongTin = new javax.swing.JPanel();
        lb_TraCuuDienNuoc_Nha = new javax.swing.JLabel();
        lb_TraCuuDienNuoc_Phong = new javax.swing.JLabel();
        cb_TraCuuDienNuoc_Nha = new javax.swing.JComboBox<>();
        cb_TraCuuDienNuoc_Phong = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_TraCuuDienNuoc = new javax.swing.JTable();
        scrollPanel_DangNhap = new javax.swing.JScrollPane();
        pn_DangNhap = new javax.swing.JPanel();
        lb_DangNhap = new javax.swing.JLabel();
        btn_DangNhap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tab_TraCuu.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tab_TraCuu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tab_TraCuu.setPreferredSize(new java.awt.Dimension(1163, 592));

        pn_CapNhatThongTinSinhVien.setBackground(new java.awt.Color(255, 255, 255));

        lb_CapNhatThongTinSV_HoSoSV.setBackground(new java.awt.Color(0, 153, 255));
        lb_CapNhatThongTinSV_HoSoSV.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_CapNhatThongTinSV_HoSoSV.setForeground(new java.awt.Color(255, 255, 255));
        lb_CapNhatThongTinSV_HoSoSV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_CapNhatThongTinSV_HoSoSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/student_32.png"))); // NOI18N
        lb_CapNhatThongTinSV_HoSoSV.setText("HỒ SƠ SINH VIÊN");
        lb_CapNhatThongTinSV_HoSoSV.setOpaque(true);

        pn_CapNhatThongTinSV_ThongTin.setBackground(new java.awt.Color(255, 255, 255));
        pn_CapNhatThongTinSV_ThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))), "Thông Tin"));

        lb_CapNhatThongTinSV_HoSinhVien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_CapNhatThongTinSV_HoSinhVien.setText("Họ Sinh Viên:");

        lb_CapNhatThongTinSV_ThongTin_TenSV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_CapNhatThongTinSV_ThongTin_TenSV.setText("Tên Sinh Viên:");

        lb_CapNhatThongTinSV_ThongTin_CMND.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_CapNhatThongTinSV_ThongTin_CMND.setText("CMND:");

        lb_CapNhatThongTinSV_ThongTin_NgaySinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_CapNhatThongTinSV_ThongTin_NgaySinh.setText("Ngày Sinh:");

        lb_CapNhatThongTinSV_ThongTin_GioiTinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_CapNhatThongTinSV_ThongTin_GioiTinh.setText("Giới Tính:");

        lb_CapNhatThongTinSV_ThongTin_NgayCap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_CapNhatThongTinSV_ThongTin_NgayCap.setText("Ngày Cấp:");

        lb_CapNhatThongTinSV_ThongTin_MSSV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_CapNhatThongTinSV_ThongTin_MSSV.setText("MSSV:");

        lb_CapNhatThongTinSV_ThongTin_Truong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_CapNhatThongTinSV_ThongTin_Truong.setText("Trường:");

        btn_CapNhatThongTinSV_ThongTin_Luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checked.png"))); // NOI18N
        btn_CapNhatThongTinSV_ThongTin_Luu.setText("Lưu");
        btn_CapNhatThongTinSV_ThongTin_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhatThongTinSV_ThongTin_LuuActionPerformed(evt);
            }
        });

        btn_CapNhatThongTinSV_ThongTin_Huy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/unchecked.png"))); // NOI18N
        btn_CapNhatThongTinSV_ThongTin_Huy.setText("Hủy");
        btn_CapNhatThongTinSV_ThongTin_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhatThongTinSV_ThongTin_HuyActionPerformed(evt);
            }
        });

        lb_CapNhatThongTinSV_ThongTin_Tinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_CapNhatThongTinSV_ThongTin_Tinh.setText("Tỉnh/TP:");

        lb_CapNhatThongTinSV_ThongTin_TonGiao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_CapNhatThongTinSV_ThongTin_TonGiao.setText("Tôn Giáo:");

        lb_CapNhatThongTinSV_ThongTin_QuocTich.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_CapNhatThongTinSV_ThongTin_QuocTich.setText("Quốc Tịch:");

        lb_CapNhatThongTinSV_ThongTin_DanToc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_CapNhatThongTinSV_ThongTin_DanToc.setText("Dân Tộc:");

        lb_CapNhatThongTinSV_ThongTin_SDT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_CapNhatThongTinSV_ThongTin_SDT.setText("Số Điện Thoại:");

        lb_CapNhatThongTinSV_ThongTin_DiaChiNha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_CapNhatThongTinSV_ThongTin_DiaChiNha.setText("Địa Chỉ Nhà:");

        javax.swing.GroupLayout pn_CapNhatThongTinSV_ThongTinLayout = new javax.swing.GroupLayout(pn_CapNhatThongTinSV_ThongTin);
        pn_CapNhatThongTinSV_ThongTin.setLayout(pn_CapNhatThongTinSV_ThongTinLayout);
        pn_CapNhatThongTinSV_ThongTinLayout.setHorizontalGroup(
            pn_CapNhatThongTinSV_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_CapNhatThongTinSV_HoSinhVien)
                    .addComponent(lb_CapNhatThongTinSV_ThongTin_CMND)
                    .addComponent(lb_CapNhatThongTinSV_ThongTin_NgaySinh)
                    .addComponent(lb_CapNhatThongTinSV_ThongTin_MSSV)
                    .addComponent(lb_CapNhatThongTinSV_ThongTin_Truong))
                .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_CapNhatThongTinSV_ThongTinLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(cb_CapNhatThongTinSV_Truong, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_CapNhatThongTinSV_ThongTin_HoSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_CapNhatThongTinSV_CMND, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateChooser_CapNhatThongTinSV_ThongTin_NgaySinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_CapNhatThongTinSV_MSSV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_CapNhatThongTinSV_ThongTin_TenSV)
                    .addComponent(lb_CapNhatThongTinSV_ThongTin_NgayCap)
                    .addComponent(lb_CapNhatThongTinSV_ThongTin_GioiTinh)
                    .addComponent(lb_CapNhatThongTinSV_ThongTin_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_CapNhatThongTinSV_ThongTin_TenSV, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(dateChooser_CapNhatThongTinSV_ThongTin_NgayCap, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(tf_CapNhatThongTinSV_ThongTin_SDT)
                    .addComponent(tf_CapNhatThongTinSV_GioiTinh))
                .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_CapNhatThongTinSV_ThongTinLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_CapNhatThongTinSV_ThongTin_QuocTich)
                            .addComponent(lb_CapNhatThongTinSV_ThongTin_DanToc)
                            .addComponent(lb_CapNhatThongTinSV_ThongTin_DiaChiNha))
                        .addGap(47, 47, 47)
                        .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createSequentialGroup()
                                .addComponent(tf_CapNhatThongTinSV_ThongTin_DanToc, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_CapNhatThongTinSV_ThongTin_Tinh)
                                    .addComponent(lb_CapNhatThongTinSV_ThongTin_TonGiao))
                                .addGap(40, 40, 40)
                                .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_CapNhatThongTinSV_ThongTin_TonGiao, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                    .addComponent(cb_CapNhatThongTinSV_ThongTin_Tinh, 0, 1, Short.MAX_VALUE)))
                            .addComponent(tf_CapNhatThongTinSV_ThongTin_QuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_CapNhatThongTinSV_ThongTin_DiaChiNha))
                        .addGap(110, 110, 110))
                    .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(btn_CapNhatThongTinSV_ThongTin_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btn_CapNhatThongTinSV_ThongTin_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pn_CapNhatThongTinSV_ThongTinLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dateChooser_CapNhatThongTinSV_ThongTin_NgayCap, tf_CapNhatThongTinSV_ThongTin_TenSV});

        pn_CapNhatThongTinSV_ThongTinLayout.setVerticalGroup(
            pn_CapNhatThongTinSV_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createSequentialGroup()
                .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_CapNhatThongTinSV_HoSinhVien)
                    .addComponent(tf_CapNhatThongTinSV_ThongTin_HoSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_CapNhatThongTinSV_ThongTin_TonGiao)
                    .addComponent(lb_CapNhatThongTinSV_ThongTin_DanToc)
                    .addComponent(tf_CapNhatThongTinSV_ThongTin_DanToc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_CapNhatThongTinSV_ThongTin_TonGiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_CapNhatThongTinSV_ThongTin_QuocTich)
                        .addComponent(tf_CapNhatThongTinSV_ThongTin_QuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_CapNhatThongTinSV_ThongTin_Tinh)
                        .addComponent(cb_CapNhatThongTinSV_ThongTin_Tinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_CapNhatThongTinSV_ThongTin_CMND)
                            .addComponent(tf_CapNhatThongTinSV_CMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createSequentialGroup()
                        .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_CapNhatThongTinSV_ThongTin_NgaySinh)
                            .addComponent(tf_CapNhatThongTinSV_ThongTin_DiaChiNha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_CapNhatThongTinSV_ThongTin_DiaChiNha))
                        .addContainerGap(147, Short.MAX_VALUE))
                    .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createSequentialGroup()
                        .addComponent(dateChooser_CapNhatThongTinSV_ThongTin_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_CapNhatThongTinSV_ThongTin_MSSV)
                            .addComponent(tf_CapNhatThongTinSV_MSSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_CapNhatThongTinSV_ThongTin_Truong)
                            .addComponent(cb_CapNhatThongTinSV_Truong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_CapNhatThongTinSV_ThongTinLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_CapNhatThongTinSV_ThongTin_Luu)
                            .addComponent(btn_CapNhatThongTinSV_ThongTin_Huy))
                        .addGap(28, 28, 28))))
            .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createSequentialGroup()
                .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_CapNhatThongTinSV_ThongTin_TenSV)
                    .addComponent(tf_CapNhatThongTinSV_ThongTin_TenSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_CapNhatThongTinSV_ThongTin_NgayCap)
                    .addComponent(dateChooser_CapNhatThongTinSV_ThongTin_NgayCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_CapNhatThongTinSV_ThongTin_GioiTinh)
                    .addComponent(tf_CapNhatThongTinSV_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(pn_CapNhatThongTinSV_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_CapNhatThongTinSV_ThongTin_SDT)
                    .addComponent(tf_CapNhatThongTinSV_ThongTin_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tf_CapNhatThongTinSV_MaKTX.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_CapNhatThongTinSV_MaKTX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_CapNhatThongTinSV_MaKTXActionPerformed(evt);
            }
        });

        btn_CapNhatThongTinSV_Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search-engine.png"))); // NOI18N
        btn_CapNhatThongTinSV_Search.setText("Search");
        btn_CapNhatThongTinSV_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhatThongTinSV_SearchActionPerformed(evt);
            }
        });

        tb_CapNhatThongTinSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã KTX", "MSSV", "Họ Sinh Viên", "Tên Sinh Viên", "Giới Tính", "Ngày Sinh", "CMND", "Ngày Cấp", "Trường", "SĐT", "Địa Chỉ Nhà", "Tỉnh", "Dân Tộc", "Tôn Giáo", "Quốc Tịch"
            }
        ));
        tb_CapNhatThongTinSV.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tb_CapNhatThongTinSV);

        lb_CapNhatThongTinSV_MaKTX.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_CapNhatThongTinSV_MaKTX.setText("Mã KTX:");

        javax.swing.GroupLayout pn_CapNhatThongTinSinhVienLayout = new javax.swing.GroupLayout(pn_CapNhatThongTinSinhVien);
        pn_CapNhatThongTinSinhVien.setLayout(pn_CapNhatThongTinSinhVienLayout);
        pn_CapNhatThongTinSinhVienLayout.setHorizontalGroup(
            pn_CapNhatThongTinSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
            .addComponent(lb_CapNhatThongTinSV_HoSoSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_CapNhatThongTinSV_ThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_CapNhatThongTinSinhVienLayout.createSequentialGroup()
                .addGap(361, 361, 361)
                .addComponent(lb_CapNhatThongTinSV_MaKTX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_CapNhatThongTinSV_MaKTX, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_CapNhatThongTinSV_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_CapNhatThongTinSinhVienLayout.setVerticalGroup(
            pn_CapNhatThongTinSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_CapNhatThongTinSinhVienLayout.createSequentialGroup()
                .addComponent(lb_CapNhatThongTinSV_HoSoSV, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(pn_CapNhatThongTinSV_ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_CapNhatThongTinSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_CapNhatThongTinSV_MaKTX, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_CapNhatThongTinSV_MaKTX)
                    .addComponent(btn_CapNhatThongTinSV_Search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );

        scrollPanel_CapNhat.setViewportView(pn_CapNhatThongTinSinhVien);

        tab_TraCuu.addTab("Cập Nhật Thông Tin Sinh Viên", new javax.swing.ImageIcon(getClass().getResource("/Images/Refresh-icon.png")), scrollPanel_CapNhat); // NOI18N

        pn_TraCuuSV.setBackground(new java.awt.Color(255, 255, 255));

        lb_TraCuuSV_TabTraCuuSV.setBackground(new java.awt.Color(0, 153, 255));
        lb_TraCuuSV_TabTraCuuSV.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_TraCuuSV_TabTraCuuSV.setForeground(new java.awt.Color(255, 255, 255));
        lb_TraCuuSV_TabTraCuuSV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_TraCuuSV_TabTraCuuSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/student_32.png"))); // NOI18N
        lb_TraCuuSV_TabTraCuuSV.setText("TRA CỨU SINH VIÊN");
        lb_TraCuuSV_TabTraCuuSV.setOpaque(true);

        tf_TraCuuSV_TabTraCuuSV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_TraCuuSV_TabTraCuuSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_TraCuuSV_TabTraCuuSVActionPerformed(evt);
            }
        });

        btn_Search_TabTraCuuSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search-engine.png"))); // NOI18N
        btn_Search_TabTraCuuSV.setText("Search");
        btn_Search_TabTraCuuSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Search_TabTraCuuSVActionPerformed(evt);
            }
        });

        tb_TraCuuSV_TabTraCuuSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã KTX", "Họ", "Tên", "Giới Tính", "Ngày Sinh", "MSSV", "Trường", "Phòng", "Nhà", "Tỉnh", "Dân Tộc", "Tôn Giáo", "Quốc Tịch"
            }
        ));
        jScrollPane1.setViewportView(tb_TraCuuSV_TabTraCuuSV);

        javax.swing.GroupLayout pn_TraCuuSVLayout = new javax.swing.GroupLayout(pn_TraCuuSV);
        pn_TraCuuSV.setLayout(pn_TraCuuSVLayout);
        pn_TraCuuSVLayout.setHorizontalGroup(
            pn_TraCuuSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1316, Short.MAX_VALUE)
            .addComponent(lb_TraCuuSV_TabTraCuuSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_TraCuuSVLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tf_TraCuuSV_TabTraCuuSV, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btn_Search_TabTraCuuSV, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(386, 386, 386))
        );
        pn_TraCuuSVLayout.setVerticalGroup(
            pn_TraCuuSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TraCuuSVLayout.createSequentialGroup()
                .addComponent(lb_TraCuuSV_TabTraCuuSV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(pn_TraCuuSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_TraCuuSV_TabTraCuuSV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Search_TabTraCuuSV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        scrollPanel_TraCuuSV.setViewportView(pn_TraCuuSV);

        tab_TraCuu.addTab("Tra Cứu Sinh Viên", new javax.swing.ImageIcon(getClass().getResource("/Images/collaboration.png")), scrollPanel_TraCuuSV); // NOI18N

        pn_TraCuuPhong.setBackground(new java.awt.Color(255, 255, 255));

        lb_TraCuuPhong.setBackground(new java.awt.Color(0, 153, 255));
        lb_TraCuuPhong.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        lb_TraCuuPhong.setForeground(new java.awt.Color(255, 255, 255));
        lb_TraCuuPhong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_TraCuuPhong.setText("TRA CỨU PHÒNG");
        lb_TraCuuPhong.setOpaque(true);

        lb_TraCuuPhong_Nha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_TraCuuPhong_Nha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cityscape.png"))); // NOI18N
        lb_TraCuuPhong_Nha.setText("Nhà: ");

        cb_TraCuuPhong_Nha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_TraCuuPhong_NhaActionPerformed(evt);
            }
        });

        lb_TraCuuPhong_Phong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_TraCuuPhong_Phong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/house.png"))); // NOI18N
        lb_TraCuuPhong_Phong.setText("Phòng:");

        cb_TraCuuPhong_Phong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_TraCuuPhong_PhongActionPerformed(evt);
            }
        });

        tb_TraCuuPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tb_TraCuuPhong);

        javax.swing.GroupLayout pn_TraCuuPhongLayout = new javax.swing.GroupLayout(pn_TraCuuPhong);
        pn_TraCuuPhong.setLayout(pn_TraCuuPhongLayout);
        pn_TraCuuPhongLayout.setHorizontalGroup(
            pn_TraCuuPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1316, Short.MAX_VALUE)
            .addGroup(pn_TraCuuPhongLayout.createSequentialGroup()
                .addGap(424, 424, 424)
                .addComponent(lb_TraCuuPhong_Nha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_TraCuuPhong_Nha, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(lb_TraCuuPhong_Phong)
                .addGap(18, 18, 18)
                .addComponent(cb_TraCuuPhong_Phong, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lb_TraCuuPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_TraCuuPhongLayout.setVerticalGroup(
            pn_TraCuuPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TraCuuPhongLayout.createSequentialGroup()
                .addComponent(lb_TraCuuPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(pn_TraCuuPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_TraCuuPhong_Nha)
                    .addComponent(cb_TraCuuPhong_Nha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_TraCuuPhong_Phong)
                    .addComponent(cb_TraCuuPhong_Phong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE))
        );

        scrollPanel_TraCuuPhong.setViewportView(pn_TraCuuPhong);

        tab_TraCuu.addTab("Tra Cứu Phòng", new javax.swing.ImageIcon(getClass().getResource("/Images/house.png")), scrollPanel_TraCuuPhong); // NOI18N

        pn_TraCuuDienNuoc.setBackground(new java.awt.Color(255, 255, 255));

        lb_TraCuuDienNuoc.setBackground(new java.awt.Color(0, 153, 255));
        lb_TraCuuDienNuoc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_TraCuuDienNuoc.setForeground(new java.awt.Color(255, 255, 255));
        lb_TraCuuDienNuoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_TraCuuDienNuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/light-bulb.png"))); // NOI18N
        lb_TraCuuDienNuoc.setText("THÔNG TIN ĐIỆN NƯỚC");
        lb_TraCuuDienNuoc.setOpaque(true);

        pn_TraCuuDienNuoc_ThongTin.setBackground(new java.awt.Color(255, 255, 255));
        pn_TraCuuDienNuoc_ThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thông Tin"));

        lb_TraCuuDienNuoc_Nha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_TraCuuDienNuoc_Nha.setText("Khối Nhà:");

        lb_TraCuuDienNuoc_Phong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_TraCuuDienNuoc_Phong.setText("Phòng:");

        cb_TraCuuDienNuoc_Nha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_TraCuuDienNuoc_NhaActionPerformed(evt);
            }
        });

        cb_TraCuuDienNuoc_Phong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_TraCuuDienNuoc_PhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_TraCuuDienNuoc_ThongTinLayout = new javax.swing.GroupLayout(pn_TraCuuDienNuoc_ThongTin);
        pn_TraCuuDienNuoc_ThongTin.setLayout(pn_TraCuuDienNuoc_ThongTinLayout);
        pn_TraCuuDienNuoc_ThongTinLayout.setHorizontalGroup(
            pn_TraCuuDienNuoc_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TraCuuDienNuoc_ThongTinLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pn_TraCuuDienNuoc_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_TraCuuDienNuoc_Nha)
                    .addComponent(lb_TraCuuDienNuoc_Phong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(pn_TraCuuDienNuoc_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_TraCuuDienNuoc_Phong, 0, 135, Short.MAX_VALUE)
                    .addComponent(cb_TraCuuDienNuoc_Nha, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 57, Short.MAX_VALUE))
        );
        pn_TraCuuDienNuoc_ThongTinLayout.setVerticalGroup(
            pn_TraCuuDienNuoc_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TraCuuDienNuoc_ThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_TraCuuDienNuoc_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_TraCuuDienNuoc_Nha)
                    .addComponent(cb_TraCuuDienNuoc_Nha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pn_TraCuuDienNuoc_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_TraCuuDienNuoc_ThongTinLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(lb_TraCuuDienNuoc_Phong)
                        .addGap(28, 28, 28))
                    .addGroup(pn_TraCuuDienNuoc_ThongTinLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cb_TraCuuDienNuoc_Phong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tb_TraCuuDienNuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tb_TraCuuDienNuoc);

        javax.swing.GroupLayout pn_TraCuuDienNuocLayout = new javax.swing.GroupLayout(pn_TraCuuDienNuoc);
        pn_TraCuuDienNuoc.setLayout(pn_TraCuuDienNuocLayout);
        pn_TraCuuDienNuocLayout.setHorizontalGroup(
            pn_TraCuuDienNuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(pn_TraCuuDienNuocLayout.createSequentialGroup()
                .addGap(429, 429, 429)
                .addComponent(pn_TraCuuDienNuoc_ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(523, Short.MAX_VALUE))
            .addComponent(lb_TraCuuDienNuoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_TraCuuDienNuocLayout.setVerticalGroup(
            pn_TraCuuDienNuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TraCuuDienNuocLayout.createSequentialGroup()
                .addComponent(lb_TraCuuDienNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(pn_TraCuuDienNuoc_ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        scrollPanel_TraCuuDienNuoc.setViewportView(pn_TraCuuDienNuoc);

        tab_TraCuu.addTab("Thông Tin Điện Nước", new javax.swing.ImageIcon(getClass().getResource("/Images/light-bulb.png")), scrollPanel_TraCuuDienNuoc); // NOI18N

        pn_DangNhap.setBackground(new java.awt.Color(255, 255, 255));
        pn_DangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_DangNhapMouseClicked(evt);
            }
        });

        lb_DangNhap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_DangNhap.setText("Click vào đây để  chuyển sang trang đăng nhập >>");

        btn_DangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login.png"))); // NOI18N
        btn_DangNhap.setText("Đăng Nhập");
        btn_DangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_DangNhapLayout = new javax.swing.GroupLayout(pn_DangNhap);
        pn_DangNhap.setLayout(pn_DangNhapLayout);
        pn_DangNhapLayout.setHorizontalGroup(
            pn_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_DangNhapLayout.createSequentialGroup()
                .addContainerGap(317, Short.MAX_VALUE)
                .addComponent(lb_DangNhap)
                .addGap(40, 40, 40)
                .addComponent(btn_DangNhap)
                .addGap(518, 518, 518))
        );
        pn_DangNhapLayout.setVerticalGroup(
            pn_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_DangNhapLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(pn_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_DangNhap)
                    .addComponent(lb_DangNhap))
                .addContainerGap(496, Short.MAX_VALUE))
        );

        scrollPanel_DangNhap.setViewportView(pn_DangNhap);

        tab_TraCuu.addTab("Đăng Nhập", new javax.swing.ImageIcon(getClass().getResource("/Images/login.png")), scrollPanel_DangNhap); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_TraCuu, javax.swing.GroupLayout.DEFAULT_SIZE, 1321, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_TraCuu, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void pn_DangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_DangNhapMouseClicked
    // TODO add your handling code here:
    DangNhapFrame dangNhapFrame = new DangNhapFrame();
    dangNhapFrame.setVisible(true);
  }//GEN-LAST:event_pn_DangNhapMouseClicked

  private void btn_DangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangNhapActionPerformed
    // TODO add your handling code here:
    DangNhapFrame dangNhapFrame = new DangNhapFrame();
    dangNhapFrame.setVisible(true);
    dangNhapFrame.setLocationRelativeTo(null);
    this.setVisible(false);

  }//GEN-LAST:event_btn_DangNhapActionPerformed

  private void cb_TraCuuDienNuoc_PhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_TraCuuDienNuoc_PhongActionPerformed
    // TODO add your handling code here:

    if (cb_TraCuuDienNuoc_Nha.getSelectedItem() == null || cb_TraCuuDienNuoc_Phong.getSelectedItem() == null) {
      return;
    }

    String tenNha = cb_TraCuuDienNuoc_Nha.getSelectedItem().toString().trim();
    String tenPhong = cb_TraCuuDienNuoc_Phong.getSelectedItem().toString().trim();

    showTable_TraCuuDN(tenNha, tenPhong);
  }//GEN-LAST:event_cb_TraCuuDienNuoc_PhongActionPerformed

  private void cb_TraCuuDienNuoc_NhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_TraCuuDienNuoc_NhaActionPerformed
    Object obj = cb_TraCuuDienNuoc_Nha.getSelectedItem();

    if (obj == null) {
      System.out.println(cb_TraCuuDienNuoc_Nha.getName() + " Error!:");
    } else {
      cb_TraCuuDienNuoc_Phong.removeAllItems();
      showComboBoxPhong(obj.toString(), cb_TraCuuDienNuoc_Phong);
    }
  }//GEN-LAST:event_cb_TraCuuDienNuoc_NhaActionPerformed

  private void cb_TraCuuPhong_PhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_TraCuuPhong_PhongActionPerformed
    // TODO add your handling code here:
    if (cb_TraCuuPhong_Phong.getSelectedItem() == null || cb_TraCuuPhong_Nha.getSelectedItem() == null) {
      return;
    }

    String tenNha = cb_TraCuuPhong_Nha.getSelectedItem().toString().trim();
    String tenPhong = cb_TraCuuPhong_Phong.getSelectedItem().toString().trim();

    ShowTable_TraCuuPhong(tenNha, tenPhong);
  }//GEN-LAST:event_cb_TraCuuPhong_PhongActionPerformed

  private void cb_TraCuuPhong_NhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_TraCuuPhong_NhaActionPerformed
    // TODO add your handling code here:
    Object obj = cb_TraCuuPhong_Nha.getSelectedItem();

    if (obj == null) {
      System.out.println(cb_TraCuuPhong_Nha.getName() + " Error!:");
    } else {
      cb_TraCuuPhong_Phong.removeAllItems();
      showComboBoxPhong_TraCuuPhong((String) obj.toString());
    }
  }//GEN-LAST:event_cb_TraCuuPhong_NhaActionPerformed

  private void btn_Search_TabTraCuuSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Search_TabTraCuuSVActionPerformed
    // TODO add your handling code here:

    String clue = tf_TraCuuSV_TabTraCuuSV.getText().trim();
    if (!"".equals(tf_TraCuuSV_TabTraCuuSV.getText().trim())) {
      ShowTable_TraCuuSinhVien(clue);
    }
  }//GEN-LAST:event_btn_Search_TabTraCuuSVActionPerformed

  private void tf_TraCuuSV_TabTraCuuSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_TraCuuSV_TabTraCuuSVActionPerformed
    // TODO add your handling code here:
    String clue = tf_TraCuuSV_TabTraCuuSV.getText().trim();
    if (!"".equals(tf_TraCuuSV_TabTraCuuSV.getText().trim())) {
      ShowTable_TraCuuSinhVien(clue);
    }
  }//GEN-LAST:event_tf_TraCuuSV_TabTraCuuSVActionPerformed

  private void btn_CapNhatThongTinSV_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhatThongTinSV_SearchActionPerformed
    // TODO add your handling code here:

    SinhVienBLL sinhVienBLL = new SinhVienBLL();
    SinhVienEntity sinhVienEntity = sinhVienBLL.Search_SV_MaKTX(tf_CapNhatThongTinSV_MaKTX.getText().trim());
    TruongBLL truongLL = new TruongBLL();
    TinhBLL tinhBLL = new TinhBLL();
    if (sinhVienEntity.getMaKTX() == null) {
      JOptionPane.showMessageDialog(this, "Không tìm thấy sinh viên");
      return;
    }

    tf_CapNhatThongTinSV_ThongTin_HoSinhVien.setText(sinhVienEntity.getHoSinhVien());
    tf_CapNhatThongTinSV_ThongTin_TenSV.setText(sinhVienEntity.getTenSinhVien());
    tf_CapNhatThongTinSV_CMND.setText(sinhVienEntity.getCMND());
    dateChooser_CapNhatThongTinSV_ThongTin_NgayCap.setDate(sinhVienEntity.getNgayCap());
    dateChooser_CapNhatThongTinSV_ThongTin_NgaySinh.setDate(sinhVienEntity.getNgaySinh());
    tf_CapNhatThongTinSV_GioiTinh.setText(sinhVienEntity.getGioiTinh());
    tf_CapNhatThongTinSV_MSSV.setText(sinhVienEntity.getMSSV());
    cb_CapNhatThongTinSV_Truong.setSelectedItem(truongLL.LayTenTruong(sinhVienEntity.getMaTruong()));
    tf_CapNhatThongTinSV_ThongTin_SDT.setText(sinhVienEntity.getSoDienThoai());
    tf_CapNhatThongTinSV_ThongTin_DanToc.setText(sinhVienEntity.getDanToc());
    tf_CapNhatThongTinSV_ThongTin_TonGiao.setText(sinhVienEntity.getTonGiao());
    tf_CapNhatThongTinSV_ThongTin_QuocTich.setText(sinhVienEntity.getQuocTich());
    cb_CapNhatThongTinSV_ThongTin_Tinh.setSelectedItem(tinhBLL.LayTenTinh(sinhVienEntity.getMaTinh()));
    tf_CapNhatThongTinSV_ThongTin_DiaChiNha.setText(sinhVienEntity.getDiaChiNha());

    SinhVienEntity SVEntity = sinhVienBLL.Search_SV_MaKTX(tf_CapNhatThongTinSV_MaKTX.getText().trim());
    if (SVEntity.getDanToc() != null || SVEntity.getTonGiao() != null || SVEntity.getQuocTich() != null || SVEntity.getDiaChiNha() != null
      || SVEntity.getSoDienThoai() != null || SVEntity.getMaTinh() != 0) {
      JOptionPane.showMessageDialog(this, "Mỗi sinh viên chỉ được cập nhật thông tin một lần.\nVui lòng liên hệ nhân viên để cập nhật thông tin.");
      return;
    }

    ShowTable_CapNhatThongTinSinhVien(tf_CapNhatThongTinSV_MaKTX.getText().trim());
  }//GEN-LAST:event_btn_CapNhatThongTinSV_SearchActionPerformed

  private void tf_CapNhatThongTinSV_MaKTXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_CapNhatThongTinSV_MaKTXActionPerformed
    // TODO add your handling code here:

    SinhVienBLL sinhVienBLL = new SinhVienBLL();
    SinhVienEntity sinhVienEntity = sinhVienBLL.Search_SV_MaKTX(tf_CapNhatThongTinSV_MaKTX.getText().trim());
    TruongBLL truongLL = new TruongBLL();
    TinhBLL tinhBLL = new TinhBLL();
    if (sinhVienEntity.getMaKTX() == null) {
      JOptionPane.showMessageDialog(this, "Không tìm thấy sinh viên");
      return;
    }

    tf_CapNhatThongTinSV_ThongTin_HoSinhVien.setText(sinhVienEntity.getHoSinhVien());
    tf_CapNhatThongTinSV_ThongTin_TenSV.setText(sinhVienEntity.getTenSinhVien());
    tf_CapNhatThongTinSV_CMND.setText(sinhVienEntity.getCMND());
    dateChooser_CapNhatThongTinSV_ThongTin_NgayCap.setDate(sinhVienEntity.getNgayCap());
    dateChooser_CapNhatThongTinSV_ThongTin_NgaySinh.setDate(sinhVienEntity.getNgaySinh());
    tf_CapNhatThongTinSV_GioiTinh.setText(sinhVienEntity.getGioiTinh());
    tf_CapNhatThongTinSV_MSSV.setText(sinhVienEntity.getMSSV());
    cb_CapNhatThongTinSV_Truong.setSelectedItem(truongLL.LayTenTruong(sinhVienEntity.getMaTruong()));
    tf_CapNhatThongTinSV_ThongTin_SDT.setText(sinhVienEntity.getSoDienThoai());
    tf_CapNhatThongTinSV_ThongTin_DanToc.setText(sinhVienEntity.getDanToc());
    tf_CapNhatThongTinSV_ThongTin_TonGiao.setText(sinhVienEntity.getTonGiao());
    tf_CapNhatThongTinSV_ThongTin_QuocTich.setText(sinhVienEntity.getQuocTich());
    cb_CapNhatThongTinSV_ThongTin_Tinh.setSelectedItem(tinhBLL.LayTenTinh(sinhVienEntity.getMaTinh()));
    tf_CapNhatThongTinSV_ThongTin_DiaChiNha.setText(sinhVienEntity.getDiaChiNha());

    SinhVienEntity SVEntity = sinhVienBLL.Search_SV_MaKTX(tf_CapNhatThongTinSV_MaKTX.getText().trim());
    if (SVEntity.getDanToc() != null || SVEntity.getTonGiao() != null || SVEntity.getQuocTich() != null || SVEntity.getDiaChiNha() != null
      || SVEntity.getSoDienThoai() != null || SVEntity.getMaTinh() != 0) {
      JOptionPane.showMessageDialog(this, "Mỗi sinh viên chỉ được cập nhật thông tin một lần.\nVui lòng liên hệ nhân viên để cập nhật thông tin.");
      return;
    }
    ShowTable_CapNhatThongTinSinhVien(tf_CapNhatThongTinSV_MaKTX.getText().trim());
  }//GEN-LAST:event_tf_CapNhatThongTinSV_MaKTXActionPerformed

  private void btn_CapNhatThongTinSV_ThongTin_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhatThongTinSV_ThongTin_HuyActionPerformed
    // TODO add your handling code here:

    tf_CapNhatThongTinSV_ThongTin_HoSinhVien.setText("");
    tf_CapNhatThongTinSV_ThongTin_TenSV.setText("");
    tf_CapNhatThongTinSV_CMND.setText("");
    dateChooser_CapNhatThongTinSV_ThongTin_NgayCap.setDate(null);
    dateChooser_CapNhatThongTinSV_ThongTin_NgaySinh.setDate(null);
    tf_CapNhatThongTinSV_GioiTinh.setText("");
    tf_CapNhatThongTinSV_MSSV.setText("");
    cb_CapNhatThongTinSV_Truong.setSelectedItem("");
    tf_CapNhatThongTinSV_ThongTin_SDT.setText("");
    tf_CapNhatThongTinSV_ThongTin_DanToc.setText("");
    tf_CapNhatThongTinSV_ThongTin_TonGiao.setText("");
    tf_CapNhatThongTinSV_ThongTin_QuocTich.setText("");
    cb_CapNhatThongTinSV_ThongTin_Tinh.setSelectedItem("");
    tf_CapNhatThongTinSV_ThongTin_DiaChiNha.setText("");
    tb_CapNhatThongTinSV.setModel(new DefaultTableModel());
  }//GEN-LAST:event_btn_CapNhatThongTinSV_ThongTin_HuyActionPerformed

  private void btn_CapNhatThongTinSV_ThongTin_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhatThongTinSV_ThongTin_LuuActionPerformed
    // TODO add your handling code here:

    if (tf_CapNhatThongTinSV_ThongTin_HoSinhVien.getText().isEmpty() || tf_CapNhatThongTinSV_ThongTin_TenSV.getText().isEmpty()) {
      JOptionPane.showMessageDialog(this, "Không được để trống họ tên sinh viên");
      return;
    }

    if (dateChooser_CapNhatThongTinSV_ThongTin_NgaySinh.getDate() == null) {
      JOptionPane.showMessageDialog(this, "Không được để trống ngày sinh");
      return;
    }

    if (dateChooser_CapNhatThongTinSV_ThongTin_NgayCap.getDate() == null) {
      JOptionPane.showMessageDialog(this, "Không được để trống ngày cấp CMND");
      return;
    }

    if (tf_CapNhatThongTinSV_CMND.getText().isEmpty()) {
      JOptionPane.showMessageDialog(this, "Không được để trống CMND");
      return;
    }
    if (tf_CapNhatThongTinSV_GioiTinh.getText().isEmpty()) {
      JOptionPane.showMessageDialog(this, "Không được để trống Giới Tính");
      return;
    }

    if (tf_CapNhatThongTinSV_MSSV.getText().isEmpty()) {
      JOptionPane.showMessageDialog(this, "Không được để trống MSSV");
      return;
    }
    if (cb_CapNhatThongTinSV_Truong.getSelectedItem().equals("")) {
      JOptionPane.showMessageDialog(this, "Không được để trống Tên Trường");
      return;
    }

    if (tf_CapNhatThongTinSV_ThongTin_SDT.getText().isEmpty() && tf_CapNhatThongTinSV_ThongTin_DanToc.getText().isEmpty() && tf_CapNhatThongTinSV_ThongTin_TonGiao.getText().isEmpty()
      && tf_CapNhatThongTinSV_ThongTin_QuocTich.getText().isEmpty() && tf_CapNhatThongTinSV_ThongTin_DiaChiNha.getText().isEmpty() && cb_CapNhatThongTinSV_ThongTin_Tinh.getSelectedItem().toString().isEmpty()) {
      JOptionPane.showMessageDialog(this, "Vui lòng cập nhật ít nhất một trong những thông tin sau đây.\n"
        + "Dân Tộc\b Tôn Giáo\b Quốc Tịch\b Tỉnh\b Địa Chỉ Nhà\b Số Điện Thoại");
      return;
    }

    TinhBLL tinhBLL = new TinhBLL();
    TruongBLL truongBLL = new TruongBLL();
    SinhVienBLL sinhVienBLL = new SinhVienBLL();

    SinhVienEntity sinhVienEntity = new SinhVienEntity();

    sinhVienEntity.setMaKTX(tf_CapNhatThongTinSV_MaKTX.getText().trim());
    sinhVienEntity.setHoSinhVien(tf_CapNhatThongTinSV_ThongTin_HoSinhVien.getText().trim());
    sinhVienEntity.setTenSinhVien(tf_CapNhatThongTinSV_ThongTin_TenSV.getText().trim());

    java.sql.Date sqlNgayCap = new java.sql.Date(dateChooser_CapNhatThongTinSV_ThongTin_NgayCap.getDate().getTime());
    java.sql.Date sqlNgaySinh = new java.sql.Date((dateChooser_CapNhatThongTinSV_ThongTin_NgaySinh.getDate().getTime()));

    sinhVienEntity.setNgayCap(sqlNgayCap);
    sinhVienEntity.setNgaySinh(sqlNgaySinh);
    sinhVienEntity.setSoDienThoai(tf_CapNhatThongTinSV_ThongTin_SDT.getText().trim());
    sinhVienEntity.setDiaChiNha(tf_CapNhatThongTinSV_ThongTin_DiaChiNha.getText().trim());
    sinhVienEntity.setDanToc(tf_CapNhatThongTinSV_ThongTin_DanToc.getText().trim());
    sinhVienEntity.setTonGiao(tf_CapNhatThongTinSV_ThongTin_TonGiao.getText().trim());
    sinhVienEntity.setQuocTich(tf_CapNhatThongTinSV_ThongTin_QuocTich.getText().trim());
    sinhVienEntity.setMaTinh(tinhBLL.LayMaTinh(cb_CapNhatThongTinSV_ThongTin_Tinh.getSelectedItem().toString().trim()));
    sinhVienEntity.setCMND(tf_CapNhatThongTinSV_CMND.getText().trim());
    sinhVienEntity.setMSSV(tf_CapNhatThongTinSV_MSSV.getText().trim());
    sinhVienEntity.setMaTruong(truongBLL.LayMaTruong(cb_CapNhatThongTinSV_Truong.getSelectedItem().toString().trim()));
    sinhVienEntity.setGioiTinh(tf_CapNhatThongTinSV_GioiTinh.getText().trim());

    sinhVienBLL.Update(sinhVienEntity.getMaKTX(), sinhVienEntity.getHoSinhVien(), sinhVienEntity.getTenSinhVien(), sinhVienEntity.getNgayCap(), sinhVienEntity.getNgaySinh(), sinhVienEntity.getSoDienThoai(), sinhVienEntity.getDanToc(), sinhVienEntity.getTonGiao(), sinhVienEntity.getQuocTich(), sinhVienEntity.getMaTinh(), sinhVienEntity.getDiaChiNha(),
      sinhVienEntity.getCMND(), sinhVienEntity.getGioiTinh(), sinhVienEntity.getMSSV(), sinhVienEntity.getMaTruong());

    JOptionPane.showMessageDialog(this, "Cập Nhật thông tin thành công");
    ShowTable_CapNhatThongTinSinhVien(sinhVienEntity.getMaKTX());
  }//GEN-LAST:event_btn_CapNhatThongTinSV_ThongTin_LuuActionPerformed

    public void ShowCombobox_Tinh() {
        TinhBLL tinhBLL = new TinhBLL();
        ArrayList<String> danhSachTinh = tinhBLL.LayDanhSachTinh();
        for (int i = 0; i < danhSachTinh.size(); i++) {
            cb_CapNhatThongTinSV_ThongTin_Tinh.addItem(danhSachTinh.get(i));
        }
    }

    public void ShowTable_CapNhatThongTinSinhVien(String MaKTX) {
        SinhVienBLL sinhVienBLL = new SinhVienBLL();
        Vector cols = new Vector();
        Vector data = new Vector();
        sinhVienBLL.ShowTable_CapNhatThongTin(cols, data, MaKTX);
        tb_CapNhatThongTinSV.setModel(new AbstractTableModel() {
            @Override
            public int getRowCount() {
                return data.size();
            }

            @Override
            public int getColumnCount() {
                return cols.size();
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                Vector rowData = (Vector) (data.elementAt(rowIndex));
                return rowData.elementAt(columnIndex);
            }

            @Override
            public String getColumnName(int column) {
                return (String) cols.elementAt(column);
            }

        });
    }

    /**
     * Phuong thức dùng để đổ dữ liệu search vào table
     *
     * @param clue
     */
    public void ShowTable_TraCuuSinhVien(String clue) {

        SinhVienBLL svBLL = new SinhVienBLL();

        Vector cols = new Vector();
        Vector data = new Vector();

        svBLL.search_TraCuuSV(cols, data, clue);

        tb_TraCuuSV_TabTraCuuSV.setModel(new AbstractTableModel() {
            @Override
            public int getRowCount() {
                return data.size();
            }

            @Override
            public int getColumnCount() {
                return cols.size();
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                Vector rowData = (Vector) (data.elementAt(rowIndex));
                return rowData.elementAt(columnIndex);
            }

            @Override
            public String getColumnName(int column) {
                return (String) cols.elementAt(column);
            }
        });
    }

    public void ShowTable_TraCuuPhong(String tenNha, String tenPhong) {
        SinhVienBLL svBLL = new SinhVienBLL();

        Vector cols = new Vector();
        Vector data = new Vector();

        svBLL.searchSV_Nha_Phong(cols, data, tenNha, tenPhong);
        tb_TraCuuPhong.setModel(new AbstractTableModel() {
            @Override
            public int getRowCount() {
                return data.size();
            }

            @Override
            public int getColumnCount() {
                return cols.size();
            }

            @Override
            public Object getValueAt(int rowIndex, int colIndex) {
                Vector rowsData = (Vector) (data.elementAt(rowIndex));
                return rowsData.elementAt(colIndex);
            }

            @Override
            public String getColumnName(int col) {
                return (String) cols.elementAt(col);
            }
        });
    }

    /**
     * Phương thức hiện thông tin điện nước theo nhà và phòng lên trên bảng;
     *
     * @param tenNha tên nhà cần tìm;
     * @param tenPhong tên phòng cần tìm;
     */
    public void showTable_TraCuuDN(String tenNha, String tenPhong) {

        GhiNhanDienNuocBLL dnBLL = new GhiNhanDienNuocBLL();

        Vector cols = new Vector();
        Vector data = new Vector();

        dnBLL.search_TraCuuDN(cols, data, tenNha, tenPhong);
        tb_TraCuuDienNuoc.setModel(new AbstractTableModel() {
            @Override
            public int getRowCount() {
                return data.size();
            }

            @Override
            public int getColumnCount() {
                return cols.size();
            }

            @Override
            public Object getValueAt(int rowIndex, int colIndex) {
                Vector row = (Vector) data.elementAt(rowIndex);
                return row.elementAt(colIndex);
            }

            @Override
            public String getColumnName(int col) {
                return (String) cols.elementAt(col);
            }
        });
    }

    /**
     * Phương thức lấy danh sách nhà đổ vào comboBox;
     *
     * @param comboBox
     */
    public void showComboBoxNha_TraCuuPhong() {
        NhaBLL nhaBLL = new NhaBLL();
        ArrayList<String> danhSachNha = nhaBLL.LayDanhSachNha();
        for (int i = 0; i < danhSachNha.size(); i++) {
            cb_TraCuuPhong_Nha.addItem(danhSachNha.get(i));
        }
    }

    /**
     * Phương thức lấy danh sách phòng dựa vào nhà cho trước đổ vào comboBox;
     *
     * @param tenNha
     * @param comboBox
     */
    public void showComboBoxPhong_TraCuuPhong(String tenNha) {
        PhongBLL phongBLL = new PhongBLL();
        ArrayList<String> danhSachPhong = phongBLL.LayDanhSachPhong(tenNha);
        for (int i = 0; i < danhSachPhong.size(); i++) {
            cb_TraCuuPhong_Phong.addItem(danhSachPhong.get(i));
        }
    }

    public void ShowComboBoxTruong_CapNhatThongTinSV() {
        TruongBLL truongBLL = new TruongBLL();
        ArrayList<String> danhSachTruong = truongBLL.LayDanhSachTruong();
        for (int i = 0; i < danhSachTruong.size(); i++) {
            cb_CapNhatThongTinSV_Truong.addItem(danhSachTruong.get(i));
        }
    }

    /**
     * Add element danh sách các nhà vào comboBox;
     *
     * @param comboBox JComboBox cần hiện thông tin;
     */
    private void showComboBoxNha(javax.swing.JComboBox comboBox) {
        NhaBLL nhaBLL = new NhaBLL();

        ArrayList<String> danhsachNha = nhaBLL.LayDanhSachNha();
        for (int i = 0; i < danhsachNha.size(); i++) {
            comboBox.addItem(danhsachNha.get(i));
        }
    }

    /**
     * Add element danh sách các phòng theo tên nhà vào comboBox;
     *
     * @param tenNha tên nhà cần lấy danh sách phòng;
     * @param comboBox JComboBox cần hiện thông tin;
     */
    public void showComboBoxPhong(String tenNha, javax.swing.JComboBox comboBox) {
        PhongBLL pbll = new PhongBLL();

        ArrayList<String> dsPhong = pbll.LayDanhSachPhong(tenNha);
        for (int i = 0; i < dsPhong.size(); i++) {
            comboBox.addItem(dsPhong.get(i));
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame mainFrame = new MainFrame();
                mainFrame.setVisible(true);
                mainFrame.setExtendedState(mainFrame.MAXIMIZED_BOTH);
                mainFrame.setResizable(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CapNhatThongTinSV_Search;
    private javax.swing.JButton btn_CapNhatThongTinSV_ThongTin_Huy;
    private javax.swing.JButton btn_CapNhatThongTinSV_ThongTin_Luu;
    private javax.swing.JButton btn_DangNhap;
    private javax.swing.JButton btn_Search_TabTraCuuSV;
    private javax.swing.JComboBox<String> cb_CapNhatThongTinSV_ThongTin_Tinh;
    private javax.swing.JComboBox<String> cb_CapNhatThongTinSV_Truong;
    private javax.swing.JComboBox<String> cb_TraCuuDienNuoc_Nha;
    private javax.swing.JComboBox<String> cb_TraCuuDienNuoc_Phong;
    private javax.swing.JComboBox<String> cb_TraCuuPhong_Nha;
    private javax.swing.JComboBox<String> cb_TraCuuPhong_Phong;
    private com.toedter.calendar.JDateChooser dateChooser_CapNhatThongTinSV_ThongTin_NgayCap;
    private com.toedter.calendar.JDateChooser dateChooser_CapNhatThongTinSV_ThongTin_NgaySinh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lb_CapNhatThongTinSV_HoSinhVien;
    private javax.swing.JLabel lb_CapNhatThongTinSV_HoSoSV;
    private javax.swing.JLabel lb_CapNhatThongTinSV_MaKTX;
    private javax.swing.JLabel lb_CapNhatThongTinSV_ThongTin_CMND;
    private javax.swing.JLabel lb_CapNhatThongTinSV_ThongTin_DanToc;
    private javax.swing.JLabel lb_CapNhatThongTinSV_ThongTin_DiaChiNha;
    private javax.swing.JLabel lb_CapNhatThongTinSV_ThongTin_GioiTinh;
    private javax.swing.JLabel lb_CapNhatThongTinSV_ThongTin_MSSV;
    private javax.swing.JLabel lb_CapNhatThongTinSV_ThongTin_NgayCap;
    private javax.swing.JLabel lb_CapNhatThongTinSV_ThongTin_NgaySinh;
    private javax.swing.JLabel lb_CapNhatThongTinSV_ThongTin_QuocTich;
    private javax.swing.JLabel lb_CapNhatThongTinSV_ThongTin_SDT;
    private javax.swing.JLabel lb_CapNhatThongTinSV_ThongTin_TenSV;
    private javax.swing.JLabel lb_CapNhatThongTinSV_ThongTin_Tinh;
    private javax.swing.JLabel lb_CapNhatThongTinSV_ThongTin_TonGiao;
    private javax.swing.JLabel lb_CapNhatThongTinSV_ThongTin_Truong;
    private javax.swing.JLabel lb_DangNhap;
    private javax.swing.JLabel lb_TraCuuDienNuoc;
    private javax.swing.JLabel lb_TraCuuDienNuoc_Nha;
    private javax.swing.JLabel lb_TraCuuDienNuoc_Phong;
    private javax.swing.JLabel lb_TraCuuPhong;
    private javax.swing.JLabel lb_TraCuuPhong_Nha;
    private javax.swing.JLabel lb_TraCuuPhong_Phong;
    private javax.swing.JLabel lb_TraCuuSV_TabTraCuuSV;
    private javax.swing.JPanel pn_CapNhatThongTinSV_ThongTin;
    private javax.swing.JPanel pn_CapNhatThongTinSinhVien;
    private javax.swing.JPanel pn_DangNhap;
    private javax.swing.JPanel pn_TraCuuDienNuoc;
    private javax.swing.JPanel pn_TraCuuDienNuoc_ThongTin;
    private javax.swing.JPanel pn_TraCuuPhong;
    private javax.swing.JPanel pn_TraCuuSV;
    private javax.swing.JScrollPane scrollPanel_CapNhat;
    private javax.swing.JScrollPane scrollPanel_DangNhap;
    private javax.swing.JScrollPane scrollPanel_TraCuuDienNuoc;
    private javax.swing.JScrollPane scrollPanel_TraCuuPhong;
    private javax.swing.JScrollPane scrollPanel_TraCuuSV;
    private javax.swing.JTabbedPane tab_TraCuu;
    private javax.swing.JTable tb_CapNhatThongTinSV;
    private javax.swing.JTable tb_TraCuuDienNuoc;
    private javax.swing.JTable tb_TraCuuPhong;
    private javax.swing.JTable tb_TraCuuSV_TabTraCuuSV;
    private javax.swing.JTextField tf_CapNhatThongTinSV_CMND;
    private javax.swing.JTextField tf_CapNhatThongTinSV_GioiTinh;
    private javax.swing.JTextField tf_CapNhatThongTinSV_MSSV;
    private javax.swing.JTextField tf_CapNhatThongTinSV_MaKTX;
    private javax.swing.JTextField tf_CapNhatThongTinSV_ThongTin_DanToc;
    private javax.swing.JTextField tf_CapNhatThongTinSV_ThongTin_DiaChiNha;
    private javax.swing.JTextField tf_CapNhatThongTinSV_ThongTin_HoSinhVien;
    private javax.swing.JTextField tf_CapNhatThongTinSV_ThongTin_QuocTich;
    private javax.swing.JTextField tf_CapNhatThongTinSV_ThongTin_SDT;
    private javax.swing.JTextField tf_CapNhatThongTinSV_ThongTin_TenSV;
    private javax.swing.JTextField tf_CapNhatThongTinSV_ThongTin_TonGiao;
    private javax.swing.JTextField tf_TraCuuSV_TabTraCuuSV;
    // End of variables declaration//GEN-END:variables
}
