/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan;

import BLL.NhaBLL;
import BLL.PhongBLL;
import BLL.QuyDinhThoiGianBLL;
import BLL.ThuPhiNoiTruBLL;
import BLL.XepPhongBLL;
import Entities.QuyDinhThoiGianEntity;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;


public class PhongFrame extends javax.swing.JFrame {

    /**
     * Creates new form PhongFrame
     */
    public PhongFrame() {
        initComponents();
        showComboBoxNha();
    }

    public void showComboBoxNha() {
        NhaBLL nhaBLL = new NhaBLL();
        ArrayList<String> danhSachNha = nhaBLL.LayDanhSachNha();
        for (int i = 0; i < danhSachNha.size(); i++) {
            cb_TenNha.addItem(danhSachNha.get(i));
        }
    }

    private void ShowTable(String tenNha) {
        Vector cols = new Vector();
        Vector data = new Vector();
        PhongBLL phongBLL = new PhongBLL();
        phongBLL.ShowTable(cols, data, tenNha);
        tb_Phong.setModel(new AbstractTableModel() {
            @Override
            public int getRowCount() {
                return data.size();
            }

            @Override
            public int getColumnCount() {
                return cols.size();
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                Vector rowData = (Vector) (data.elementAt(rowIndex));
                return rowData.elementAt(columnIndex);
            }

            @Override
            public String getColumnName(int column) {
                return (String) cols.elementAt(column);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pn_Phong = new javax.swing.JPanel();
    lb_Phong = new javax.swing.JLabel();
    pn_Phong_ChiTiet = new javax.swing.JPanel();
    lb_TenNha = new javax.swing.JLabel();
    cb_TenNha = new javax.swing.JComboBox<>();
    lb_TenPhong = new javax.swing.JLabel();
    tf_TenPhong = new javax.swing.JTextField();
    btn_Them = new javax.swing.JButton();
    btn_Xoa = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tb_Phong = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setResizable(false);

    pn_Phong.setBackground(new java.awt.Color(255, 255, 255));

    lb_Phong.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    lb_Phong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/house.png"))); // NOI18N
    lb_Phong.setText("PHÒNG");

    pn_Phong_ChiTiet.setBackground(new java.awt.Color(255, 255, 255));
    pn_Phong_ChiTiet.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Phòng\n"));

    lb_TenNha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    lb_TenNha.setText("Nhà:");

    cb_TenNha.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cb_TenNhaActionPerformed(evt);
      }
    });

    lb_TenPhong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    lb_TenPhong.setText("Phòng:");

    javax.swing.GroupLayout pn_Phong_ChiTietLayout = new javax.swing.GroupLayout(pn_Phong_ChiTiet);
    pn_Phong_ChiTiet.setLayout(pn_Phong_ChiTietLayout);
    pn_Phong_ChiTietLayout.setHorizontalGroup(
      pn_Phong_ChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pn_Phong_ChiTietLayout.createSequentialGroup()
        .addGap(27, 27, 27)
        .addGroup(pn_Phong_ChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lb_TenPhong)
          .addComponent(lb_TenNha))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
        .addGroup(pn_Phong_ChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(tf_TenPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
          .addComponent(cb_TenNha, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(50, 50, 50))
    );
    pn_Phong_ChiTietLayout.setVerticalGroup(
      pn_Phong_ChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pn_Phong_ChiTietLayout.createSequentialGroup()
        .addGroup(pn_Phong_ChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lb_TenNha)
          .addComponent(cb_TenNha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
        .addGroup(pn_Phong_ChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(tf_TenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lb_TenPhong))
        .addContainerGap())
    );

    btn_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checked.png"))); // NOI18N
    btn_Them.setText("Thêm");
    btn_Them.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_ThemActionPerformed(evt);
      }
    });

    btn_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/unchecked.png"))); // NOI18N
    btn_Xoa.setText("Xóa");
    btn_Xoa.setToolTipText("");
    btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_XoaActionPerformed(evt);
      }
    });

    tb_Phong.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    tb_Phong.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tb_PhongMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tb_Phong);

    javax.swing.GroupLayout pn_PhongLayout = new javax.swing.GroupLayout(pn_Phong);
    pn_Phong.setLayout(pn_PhongLayout);
    pn_PhongLayout.setHorizontalGroup(
      pn_PhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
      .addGroup(pn_PhongLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btn_Them)
        .addGap(30, 30, 30)
        .addComponent(btn_Xoa)
        .addGap(119, 119, 119))
      .addGroup(pn_PhongLayout.createSequentialGroup()
        .addGroup(pn_PhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(pn_PhongLayout.createSequentialGroup()
            .addGap(166, 166, 166)
            .addComponent(pn_Phong_ChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(pn_PhongLayout.createSequentialGroup()
            .addGap(259, 259, 259)
            .addComponent(lb_Phong)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pn_PhongLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_Them, btn_Xoa});

    pn_PhongLayout.setVerticalGroup(
      pn_PhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pn_PhongLayout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addComponent(lb_Phong)
        .addGap(18, 18, 18)
        .addComponent(pn_Phong_ChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
        .addGroup(pn_PhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btn_Them)
          .addComponent(btn_Xoa))
        .addGap(18, 18, 18)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pn_PhongLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_Them, btn_Xoa});

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pn_Phong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pn_Phong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void cb_TenNhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_TenNhaActionPerformed
        // TODO add your handling code here: 
        ShowTable(cb_TenNha.getSelectedItem().toString().trim());
    }//GEN-LAST:event_cb_TenNhaActionPerformed

    private void tb_PhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_PhongMouseClicked
        // TODO add your handling code here:
        int index = tb_Phong.getSelectedRow();
        tf_TenPhong.setText(String.valueOf(tb_Phong.getValueAt(index, 1)));
    }//GEN-LAST:event_tb_PhongMouseClicked

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        if (tf_TenPhong.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên phòng muốn thêm");
            return;
        }
        PhongBLL phongBLL = new PhongBLL();
        NhaBLL nhaBLL = new NhaBLL();

        String tenNha = cb_TenNha.getSelectedItem().toString().trim();
        String tenPhong = tf_TenPhong.getText().trim();
        int maNha = nhaBLL.LayMaNha(tenNha);

        if (phongBLL.TimTenPhong(tenPhong, maNha)) {
            JOptionPane.showMessageDialog(this, "Không thể thêm. Tên Phòng đã có sẵn");
            return;
        }

        phongBLL.Insert(tenPhong, maNha);
        ShowTable(tenNha);

    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:

        if (tf_TenPhong.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên phòng hoặc chọn phòng ở bảng phía dưới.");
            return;
        }

        PhongBLL phongBLL = new PhongBLL();
        NhaBLL nhaBLL = new NhaBLL();
        ThuPhiNoiTruBLL thuPhiNoiTruBLL = new ThuPhiNoiTruBLL();
        XepPhongBLL xepPhongBLL = new XepPhongBLL();
        QuyDinhThoiGianBLL quyDinhThoiGianBLL = new QuyDinhThoiGianBLL();
        QuyDinhThoiGianEntity quyDinhThoiGianEntity = quyDinhThoiGianBLL.LayThoiGian();

        String tenNha = cb_TenNha.getSelectedItem().toString().trim();
        String tenPhong = tf_TenPhong.getText().trim();
        int maNha = nhaBLL.LayMaNha(tenNha);
        int maPhong = phongBLL.LayMaPhong(Integer.parseInt(tenPhong), tenNha);

        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa phòng " + tenPhong + " khỏi danh sách?");
        if (choice == JOptionPane.YES_OPTION) {
            if (phongBLL.TimTenPhong(tenPhong, maNha) == false) {
                JOptionPane.showMessageDialog(this, "Không thế xóa.\n Phòng này không có trong danh sách.");
                return;
            }

            if (xepPhongBLL.kiemTraXepPhong(maPhong, quyDinhThoiGianEntity.getNamHoc())) {
                JOptionPane.showMessageDialog(this, "Không thể xóa.\n phòng này đang được sử dụng trong năm học hiện tại.");
                return;
            }
            thuPhiNoiTruBLL.delete(quyDinhThoiGianEntity.getNamHoc());
            xepPhongBLL.delete(maPhong);
            phongBLL.Delete(maPhong);
            JOptionPane.showMessageDialog(this, "Xóa thành công " + tenNha + " khỏi danh sách");
            ShowTable(tenNha);
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhongFrame().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_Them;
  private javax.swing.JButton btn_Xoa;
  private javax.swing.JComboBox<String> cb_TenNha;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lb_Phong;
  private javax.swing.JLabel lb_TenNha;
  private javax.swing.JLabel lb_TenPhong;
  private javax.swing.JPanel pn_Phong;
  private javax.swing.JPanel pn_Phong_ChiTiet;
  private javax.swing.JTable tb_Phong;
  private javax.swing.JTextField tf_TenPhong;
  // End of variables declaration//GEN-END:variables
}
