/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan;

import BLL.LoaiNhaBLL;
import BLL.QuyDinhPhiNoiTruBLL;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;


public class QuyDinhPhiNoiTruFrame extends javax.swing.JFrame {

    /**
     * Creates new form QuyDinhPhiNoiTruFrame
     */
    public QuyDinhPhiNoiTruFrame() {
        initComponents();
        ShowTable();
        ShowComboBox_LoaiNha();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pn_QuyDinhPhiNoiTru = new javax.swing.JPanel();
    lb_QuyDinhPhiNoiTru = new javax.swing.JLabel();
    pn_QuyDinhPhiNoiTru_ThongTin = new javax.swing.JPanel();
    lb_LoaiPhong = new javax.swing.JLabel();
    cb_LoaiPhong = new javax.swing.JComboBox<>();
    lb_MucPhi = new javax.swing.JLabel();
    tf_MucPhi = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    tb_QuyDinhPhiNoiTru = new javax.swing.JTable();
    btn_Luu = new javax.swing.JButton();
    btn_Huy = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setResizable(false);

    pn_QuyDinhPhiNoiTru.setBackground(new java.awt.Color(255, 255, 255));

    lb_QuyDinhPhiNoiTru.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
    lb_QuyDinhPhiNoiTru.setText("QUY ĐỊNH PHÍ NỘI TRÚ");

    pn_QuyDinhPhiNoiTru_ThongTin.setBackground(new java.awt.Color(255, 255, 255));
    pn_QuyDinhPhiNoiTru_ThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thông tin"));

    lb_LoaiPhong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    lb_LoaiPhong.setText("Loại Phòng:");

    cb_LoaiPhong.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cb_LoaiPhongActionPerformed(evt);
      }
    });

    lb_MucPhi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    lb_MucPhi.setText("Mức Phí:");

    tf_MucPhi.setToolTipText("");

    javax.swing.GroupLayout pn_QuyDinhPhiNoiTru_ThongTinLayout = new javax.swing.GroupLayout(pn_QuyDinhPhiNoiTru_ThongTin);
    pn_QuyDinhPhiNoiTru_ThongTin.setLayout(pn_QuyDinhPhiNoiTru_ThongTinLayout);
    pn_QuyDinhPhiNoiTru_ThongTinLayout.setHorizontalGroup(
      pn_QuyDinhPhiNoiTru_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pn_QuyDinhPhiNoiTru_ThongTinLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lb_LoaiPhong)
        .addGap(18, 18, 18)
        .addComponent(cb_LoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(28, 28, 28)
        .addComponent(lb_MucPhi)
        .addGap(31, 31, 31)
        .addComponent(tf_MucPhi, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
        .addContainerGap())
    );
    pn_QuyDinhPhiNoiTru_ThongTinLayout.setVerticalGroup(
      pn_QuyDinhPhiNoiTru_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pn_QuyDinhPhiNoiTru_ThongTinLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pn_QuyDinhPhiNoiTru_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lb_LoaiPhong)
          .addComponent(cb_LoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lb_MucPhi)
          .addComponent(tf_MucPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(23, Short.MAX_VALUE))
    );

    tb_QuyDinhPhiNoiTru.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    tb_QuyDinhPhiNoiTru.getTableHeader().setReorderingAllowed(false);
    jScrollPane1.setViewportView(tb_QuyDinhPhiNoiTru);

    btn_Luu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    btn_Luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checked.png"))); // NOI18N
    btn_Luu.setText("Lưu");
    btn_Luu.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_LuuActionPerformed(evt);
      }
    });

    btn_Huy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    btn_Huy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/unchecked.png"))); // NOI18N
    btn_Huy.setText("Hủy");
    btn_Huy.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_HuyActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout pn_QuyDinhPhiNoiTruLayout = new javax.swing.GroupLayout(pn_QuyDinhPhiNoiTru);
    pn_QuyDinhPhiNoiTru.setLayout(pn_QuyDinhPhiNoiTruLayout);
    pn_QuyDinhPhiNoiTruLayout.setHorizontalGroup(
      pn_QuyDinhPhiNoiTruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1)
      .addGroup(pn_QuyDinhPhiNoiTruLayout.createSequentialGroup()
        .addGroup(pn_QuyDinhPhiNoiTruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(pn_QuyDinhPhiNoiTruLayout.createSequentialGroup()
            .addGap(127, 127, 127)
            .addComponent(lb_QuyDinhPhiNoiTru))
          .addGroup(pn_QuyDinhPhiNoiTruLayout.createSequentialGroup()
            .addGap(63, 63, 63)
            .addGroup(pn_QuyDinhPhiNoiTruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_QuyDinhPhiNoiTruLayout.createSequentialGroup()
                .addComponent(btn_Luu)
                .addGap(26, 26, 26)
                .addComponent(btn_Huy))
              .addComponent(pn_QuyDinhPhiNoiTru_ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(66, Short.MAX_VALUE))
    );

    pn_QuyDinhPhiNoiTruLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_Huy, btn_Luu});

    pn_QuyDinhPhiNoiTruLayout.setVerticalGroup(
      pn_QuyDinhPhiNoiTruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pn_QuyDinhPhiNoiTruLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lb_QuyDinhPhiNoiTru)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(pn_QuyDinhPhiNoiTru_ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(pn_QuyDinhPhiNoiTruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btn_Luu)
          .addComponent(btn_Huy))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pn_QuyDinhPhiNoiTruLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_Huy, btn_Luu});

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pn_QuyDinhPhiNoiTru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pn_QuyDinhPhiNoiTru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void cb_LoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_LoaiPhongActionPerformed
        // TODO add your handling code here:       
        QuyDinhPhiNoiTruBLL quyDinhPhiNoiTruBLL = new QuyDinhPhiNoiTruBLL();
        tf_MucPhi.setText(quyDinhPhiNoiTruBLL.LayPhiNoiTruTheoLoaiNha(Integer.parseInt(cb_LoaiPhong.getSelectedItem().toString().trim())));
    }//GEN-LAST:event_cb_LoaiPhongActionPerformed

    private void btn_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LuuActionPerformed
        // TODO add your handling code here:

        QuyDinhPhiNoiTruBLL quyDinhPhiNoiTruBLL = new QuyDinhPhiNoiTruBLL();
        if(tf_MucPhi.getText().equals("" ))
        {
            JOptionPane.showMessageDialog(this, "Không được để trống mức phí.");
            return;
        }
        quyDinhPhiNoiTruBLL.Update(Integer.parseInt(cb_LoaiPhong.getSelectedItem().toString().trim()),tf_MucPhi.getText().trim());
        JOptionPane.showMessageDialog(this, "Cập nhật thành công");
        ShowTable();

    }//GEN-LAST:event_btn_LuuActionPerformed

    private void btn_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuyActionPerformed
        // TODO add your handling code here:
        tf_MucPhi.setText("");
    }//GEN-LAST:event_btn_HuyActionPerformed

    public void ShowTable() {
        Vector cols = new Vector();
        Vector data = new Vector();

        QuyDinhPhiNoiTruBLL quyDinhPhiNoiTruBLL = new QuyDinhPhiNoiTruBLL();

        quyDinhPhiNoiTruBLL.ShowTable(cols, data);
        tb_QuyDinhPhiNoiTru.setModel(new AbstractTableModel() {
            @Override
            public int getRowCount() {
                return data.size();
            }

            @Override
            public int getColumnCount() {
                return cols.size();
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                Vector rowData = (Vector) (data.elementAt(rowIndex));
                return rowData.elementAt(columnIndex);
            }

            @Override
            public String getColumnName(int column) {
                return (String) cols.elementAt(column);
            }
        });
    }

    public void ShowComboBox_LoaiNha() {
        LoaiNhaBLL loaiNhaBLL = new LoaiNhaBLL();
        ArrayList<Integer> danhsachLoaiNha = loaiNhaBLL.LaySoNguoi();

        for (int i = 0; i < danhsachLoaiNha.size(); i++) {
            cb_LoaiPhong.addItem(String.valueOf(danhsachLoaiNha.get(i)));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuyDinhPhiNoiTruFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuyDinhPhiNoiTruFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuyDinhPhiNoiTruFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuyDinhPhiNoiTruFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuyDinhPhiNoiTruFrame().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_Huy;
  private javax.swing.JButton btn_Luu;
  private javax.swing.JComboBox<String> cb_LoaiPhong;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lb_LoaiPhong;
  private javax.swing.JLabel lb_MucPhi;
  private javax.swing.JLabel lb_QuyDinhPhiNoiTru;
  private javax.swing.JPanel pn_QuyDinhPhiNoiTru;
  private javax.swing.JPanel pn_QuyDinhPhiNoiTru_ThongTin;
  private javax.swing.JTable tb_QuyDinhPhiNoiTru;
  private javax.swing.JTextField tf_MucPhi;
  // End of variables declaration//GEN-END:variables
}
