/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan;

import BLL.QuyDinhMucKyLuatBLL;
import BLL.TinhBLL;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;


public class QuyDinhMucKyLuatFrame extends javax.swing.JFrame {

    /**
     * Creates new form QuyDinhMucKyLuatFrame
     */
    public QuyDinhMucKyLuatFrame() {
        initComponents();
        showTable();
    }

    public void showTable() {
        Vector cols = new Vector();
        Vector data = new Vector();
        QuyDinhMucKyLuatBLL quyDinhMucKyLuatBLL = new QuyDinhMucKyLuatBLL();

        quyDinhMucKyLuatBLL.ShowTable(cols, data);
        tb_QuyDinhKyLuat.setModel(new AbstractTableModel() {
            @Override
            public int getRowCount() {
                return data.size();
            }

            @Override
            public int getColumnCount() {
                return cols.size();
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                Vector rowData = (Vector) (data.elementAt(rowIndex));
                return rowData.elementAt(columnIndex);
            }

            @Override
            public String getColumnName(int column) {
                return (String) cols.elementAt(column);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_QuyDinhKyLuat = new javax.swing.JPanel();
        lb_QuyDinhKyLuat = new javax.swing.JLabel();
        pn_QuyDinhKyLuat_ThongTin = new javax.swing.JPanel();
        lb_MucKyLuat = new javax.swing.JLabel();
        tf_MucKyLuat = new javax.swing.JTextField();
        btn_Them = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_QuyDinhKyLuat = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pn_QuyDinhKyLuat.setBackground(new java.awt.Color(255, 255, 255));

        lb_QuyDinhKyLuat.setBackground(new java.awt.Color(255, 255, 255));
        lb_QuyDinhKyLuat.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_QuyDinhKyLuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_QuyDinhKyLuat.setText("MỨC KỶ LUẬT");
        lb_QuyDinhKyLuat.setOpaque(true);

        pn_QuyDinhKyLuat_ThongTin.setBackground(new java.awt.Color(255, 255, 255));
        pn_QuyDinhKyLuat_ThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Mức Kỷ Luật"));

        lb_MucKyLuat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_MucKyLuat.setText("Mức Kỷ Luật:");

        javax.swing.GroupLayout pn_QuyDinhKyLuat_ThongTinLayout = new javax.swing.GroupLayout(pn_QuyDinhKyLuat_ThongTin);
        pn_QuyDinhKyLuat_ThongTin.setLayout(pn_QuyDinhKyLuat_ThongTinLayout);
        pn_QuyDinhKyLuat_ThongTinLayout.setHorizontalGroup(
            pn_QuyDinhKyLuat_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_QuyDinhKyLuat_ThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_MucKyLuat, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(tf_MucKyLuat, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_QuyDinhKyLuat_ThongTinLayout.setVerticalGroup(
            pn_QuyDinhKyLuat_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_QuyDinhKyLuat_ThongTinLayout.createSequentialGroup()
                .addGroup(pn_QuyDinhKyLuat_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_MucKyLuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_MucKyLuat))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        btn_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1478723080_ok.png"))); // NOI18N
        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1478723175_nok.png"))); // NOI18N
        btn_Xoa.setText("Xóa");
        btn_Xoa.setToolTipText("");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Refresh-icon.png"))); // NOI18N
        btn_Sua.setText("Sửa");
        btn_Sua.setToolTipText("");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        tb_QuyDinhKyLuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Kỷ Luật", "Tên Kỷ Luật"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_QuyDinhKyLuat.getTableHeader().setReorderingAllowed(false);
        tb_QuyDinhKyLuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_QuyDinhKyLuatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_QuyDinhKyLuat);

        javax.swing.GroupLayout pn_QuyDinhKyLuatLayout = new javax.swing.GroupLayout(pn_QuyDinhKyLuat);
        pn_QuyDinhKyLuat.setLayout(pn_QuyDinhKyLuatLayout);
        pn_QuyDinhKyLuatLayout.setHorizontalGroup(
            pn_QuyDinhKyLuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_QuyDinhKyLuatLayout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addComponent(btn_Them)
                .addGap(18, 18, 18)
                .addComponent(btn_Xoa)
                .addGap(18, 18, 18)
                .addComponent(btn_Sua)
                .addGap(18, 18, 18))
            .addGroup(pn_QuyDinhKyLuatLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(pn_QuyDinhKyLuat_ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lb_QuyDinhKyLuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pn_QuyDinhKyLuatLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_Sua, btn_Them, btn_Xoa});

        pn_QuyDinhKyLuatLayout.setVerticalGroup(
            pn_QuyDinhKyLuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_QuyDinhKyLuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_QuyDinhKyLuat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_QuyDinhKyLuat_ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(pn_QuyDinhKyLuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Them)
                    .addComponent(btn_Xoa)
                    .addComponent(btn_Sua))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pn_QuyDinhKyLuatLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_Sua, btn_Them, btn_Xoa});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_QuyDinhKyLuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_QuyDinhKyLuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:

        String tenKyLuat = tf_MucKyLuat.getText().trim();
        QuyDinhMucKyLuatBLL quyDinhMucKyLuatBLL = new QuyDinhMucKyLuatBLL();

        if (tf_MucKyLuat.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên mức kỷ luật muốn thêm.\nSau đó bấm nút thêm");
            return;
        }
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm " + tenKyLuat + " vào danh sách?");
        if (choice == JOptionPane.YES_OPTION) {
            if (quyDinhMucKyLuatBLL.TimTenKyLuat(tenKyLuat)) {
                JOptionPane.showMessageDialog(this, "Không thể thêm.\nMức Kỷ Luật này đã có trong danh sách.");
                return;
            }
            quyDinhMucKyLuatBLL.Insert(tenKyLuat);
            showTable();
            JOptionPane.showMessageDialog(this, "Thêm thành công " + tenKyLuat + " vào danh sách");
        }

    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:

        QuyDinhMucKyLuatBLL quyDinhMucKyLuatBLL = new QuyDinhMucKyLuatBLL();
        String tenKyLuat = tf_MucKyLuat.getText().trim();
        if (tf_MucKyLuat.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên mức kỷ luật hoặc chọn ở bảng phía dưới.");
            return;
        }
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa " + tenKyLuat + " khỏi danh sách?");
        if (choice == JOptionPane.YES_OPTION) {
            if (quyDinhMucKyLuatBLL.TimTenKyLuat(tenKyLuat) == false) {
                JOptionPane.showMessageDialog(this, "Không thế xóa.\nMức kỷ luật này không có trong danh sách.");
                return;
            }

            quyDinhMucKyLuatBLL.Delete(tenKyLuat);
            showTable();
            JOptionPane.showMessageDialog(this, "Xóa thành công " + tenKyLuat + " khỏi danh sách");
        }


    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:

        QuyDinhMucKyLuatBLL quyDinhMucKyLuatBLL = new QuyDinhMucKyLuatBLL();
        String tenKyLuat = tf_MucKyLuat.getText().trim();
        if (!tb_QuyDinhKyLuat.isColumnSelected(0) && !tb_QuyDinhKyLuat.isColumnSelected(1)) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn kỷ luật ở bảng phía dưới.\nSau đó cập nhật lại tên mới ở trên.");
            return;
        }

        int index = tb_QuyDinhKyLuat.getSelectedRow();
        int maKyLuat = (int) tb_QuyDinhKyLuat.getValueAt(index, 0);

        if (tf_MucKyLuat.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn kỷ luật  ở bảng phía dưới sau đó cập nhật tên mới.");
            return;
        }

        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn cập nhật lại tên kỷ luật  được chọn?");
        if (choice == JOptionPane.YES_OPTION) {
            quyDinhMucKyLuatBLL.Update(tenKyLuat, maKyLuat);
            JOptionPane.showMessageDialog(this, "Cập nhật thành công");
            showTable();
        }
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void tb_QuyDinhKyLuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_QuyDinhKyLuatMouseClicked
        // TODO add your handling code here:

        int index = tb_QuyDinhKyLuat.getSelectedRow();
        tf_MucKyLuat.setText((String) tb_QuyDinhKyLuat.getValueAt(index, 1));
    }//GEN-LAST:event_tb_QuyDinhKyLuatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuyDinhMucKyLuatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuyDinhMucKyLuatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuyDinhMucKyLuatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuyDinhMucKyLuatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuyDinhMucKyLuatFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_MucKyLuat;
    private javax.swing.JLabel lb_QuyDinhKyLuat;
    private javax.swing.JPanel pn_QuyDinhKyLuat;
    private javax.swing.JPanel pn_QuyDinhKyLuat_ThongTin;
    private javax.swing.JTable tb_QuyDinhKyLuat;
    private javax.swing.JTextField tf_MucKyLuat;
    // End of variables declaration//GEN-END:variables
}
