/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan;

import BLL.MucGiaDienBLL;
import BLL.TinhBLL;
import Entities.MucGiaDienEntity;
import java.sql.Date;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;


public class QuyDinhGiaDienFrame extends javax.swing.JFrame {

    /**
     * Creates new form QuyDinhGiaDien
     */
    public QuyDinhGiaDienFrame() {
        initComponents();
        ShowTable();
    }

    public void ShowTable() {
        Vector cols = new Vector();
        Vector data = new Vector();
        MucGiaDienBLL mucGiaDienBLL = new MucGiaDienBLL();

        mucGiaDienBLL.ShowTable(cols, data);
        tb_QuyDinhGiaDien.setModel(new AbstractTableModel() {
            @Override
            public int getRowCount() {
                return data.size();
            }

            @Override
            public int getColumnCount() {
                return cols.size();
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                Vector rowData = (Vector) (data.elementAt(rowIndex));
                return rowData.elementAt(columnIndex);
            }

            @Override
            public String getColumnName(int column) {
                return (String) cols.elementAt(column);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pn_QuyDinhGiaDien = new javax.swing.JPanel();
    lb_QuyDinhGiaDien_GiaDien = new javax.swing.JLabel();
    pn_QuyDinhGiaDien_ThongTin = new javax.swing.JPanel();
    lb_QuyDinhGiaDien_TuKW = new javax.swing.JLabel();
    tf_QuyDinhGiaDien_TuKW = new javax.swing.JTextField();
    lb_QuyDinhGiaDien_DenKW = new javax.swing.JLabel();
    tf_QuyDinhGiaDien_DenKW = new javax.swing.JTextField();
    lb_QuyDinhGiaDien_Gia = new javax.swing.JLabel();
    tf_QuyDinhGiaDien_Gia = new javax.swing.JTextField();
    btn_QuyDinhGiaDien_Luu = new javax.swing.JButton();
    btn_QuyDinhGiaDien_huy = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tb_QuyDinhGiaDien = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setResizable(false);

    pn_QuyDinhGiaDien.setBackground(new java.awt.Color(255, 255, 255));

    lb_QuyDinhGiaDien_GiaDien.setBackground(new java.awt.Color(255, 255, 255));
    lb_QuyDinhGiaDien_GiaDien.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    lb_QuyDinhGiaDien_GiaDien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lb_QuyDinhGiaDien_GiaDien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/light-bulb.png"))); // NOI18N
    lb_QuyDinhGiaDien_GiaDien.setText("GIÁ ĐIỆN");

    pn_QuyDinhGiaDien_ThongTin.setBackground(new java.awt.Color(255, 255, 255));
    pn_QuyDinhGiaDien_ThongTin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    lb_QuyDinhGiaDien_TuKW.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    lb_QuyDinhGiaDien_TuKW.setText("Từ KW:");

    lb_QuyDinhGiaDien_DenKW.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    lb_QuyDinhGiaDien_DenKW.setText("Đến KW:");

    lb_QuyDinhGiaDien_Gia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    lb_QuyDinhGiaDien_Gia.setText("Giá:");

    javax.swing.GroupLayout pn_QuyDinhGiaDien_ThongTinLayout = new javax.swing.GroupLayout(pn_QuyDinhGiaDien_ThongTin);
    pn_QuyDinhGiaDien_ThongTin.setLayout(pn_QuyDinhGiaDien_ThongTinLayout);
    pn_QuyDinhGiaDien_ThongTinLayout.setHorizontalGroup(
      pn_QuyDinhGiaDien_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pn_QuyDinhGiaDien_ThongTinLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pn_QuyDinhGiaDien_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(pn_QuyDinhGiaDien_ThongTinLayout.createSequentialGroup()
            .addComponent(lb_QuyDinhGiaDien_TuKW)
            .addGap(18, 18, 18)
            .addComponent(tf_QuyDinhGiaDien_TuKW))
          .addGroup(pn_QuyDinhGiaDien_ThongTinLayout.createSequentialGroup()
            .addComponent(lb_QuyDinhGiaDien_DenKW)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(tf_QuyDinhGiaDien_DenKW, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
        .addComponent(lb_QuyDinhGiaDien_Gia)
        .addGap(18, 18, 18)
        .addComponent(tf_QuyDinhGiaDien_Gia, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(54, 54, 54))
    );
    pn_QuyDinhGiaDien_ThongTinLayout.setVerticalGroup(
      pn_QuyDinhGiaDien_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pn_QuyDinhGiaDien_ThongTinLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pn_QuyDinhGiaDien_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lb_QuyDinhGiaDien_TuKW)
          .addComponent(tf_QuyDinhGiaDien_TuKW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(tf_QuyDinhGiaDien_Gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lb_QuyDinhGiaDien_Gia))
        .addGap(26, 26, 26)
        .addGroup(pn_QuyDinhGiaDien_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lb_QuyDinhGiaDien_DenKW)
          .addComponent(tf_QuyDinhGiaDien_DenKW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    btn_QuyDinhGiaDien_Luu.setBackground(new java.awt.Color(255, 255, 255));
    btn_QuyDinhGiaDien_Luu.setForeground(new java.awt.Color(255, 255, 255));
    btn_QuyDinhGiaDien_Luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checked.png"))); // NOI18N
    btn_QuyDinhGiaDien_Luu.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_QuyDinhGiaDien_LuuActionPerformed(evt);
      }
    });

    btn_QuyDinhGiaDien_huy.setBackground(new java.awt.Color(255, 255, 255));
    btn_QuyDinhGiaDien_huy.setForeground(new java.awt.Color(255, 255, 255));
    btn_QuyDinhGiaDien_huy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/unchecked.png"))); // NOI18N
    btn_QuyDinhGiaDien_huy.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_QuyDinhGiaDien_huyActionPerformed(evt);
      }
    });

    tb_QuyDinhGiaDien.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    tb_QuyDinhGiaDien.setGridColor(new java.awt.Color(0, 0, 0));
    tb_QuyDinhGiaDien.getTableHeader().setReorderingAllowed(false);
    tb_QuyDinhGiaDien.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tb_QuyDinhGiaDienMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tb_QuyDinhGiaDien);

    javax.swing.GroupLayout pn_QuyDinhGiaDienLayout = new javax.swing.GroupLayout(pn_QuyDinhGiaDien);
    pn_QuyDinhGiaDien.setLayout(pn_QuyDinhGiaDienLayout);
    pn_QuyDinhGiaDienLayout.setHorizontalGroup(
      pn_QuyDinhGiaDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(lb_QuyDinhGiaDien_GiaDien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(pn_QuyDinhGiaDienLayout.createSequentialGroup()
        .addContainerGap(22, Short.MAX_VALUE)
        .addGroup(pn_QuyDinhGiaDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_QuyDinhGiaDienLayout.createSequentialGroup()
            .addComponent(btn_QuyDinhGiaDien_Luu)
            .addGap(26, 26, 26)
            .addComponent(btn_QuyDinhGiaDien_huy))
          .addComponent(pn_QuyDinhGiaDien_ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(22, Short.MAX_VALUE))
      .addComponent(jScrollPane1)
    );
    pn_QuyDinhGiaDienLayout.setVerticalGroup(
      pn_QuyDinhGiaDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pn_QuyDinhGiaDienLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lb_QuyDinhGiaDien_GiaDien)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(pn_QuyDinhGiaDien_ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(pn_QuyDinhGiaDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btn_QuyDinhGiaDien_huy, javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(btn_QuyDinhGiaDien_Luu, javax.swing.GroupLayout.Alignment.TRAILING))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pn_QuyDinhGiaDien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pn_QuyDinhGiaDien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void tb_QuyDinhGiaDienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_QuyDinhGiaDienMouseClicked
        // TODO add your handling code here:

        int index = tb_QuyDinhGiaDien.getSelectedRow();
        tf_QuyDinhGiaDien_TuKW.setText(tb_QuyDinhGiaDien.getValueAt(index, 2).toString());
        tf_QuyDinhGiaDien_DenKW.setText(tb_QuyDinhGiaDien.getValueAt(index, 3).toString());
        tf_QuyDinhGiaDien_Gia.setText(tb_QuyDinhGiaDien.getValueAt(index, 4).toString());
    }//GEN-LAST:event_tb_QuyDinhGiaDienMouseClicked

    private void btn_QuyDinhGiaDien_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuyDinhGiaDien_LuuActionPerformed
        // TODO add your handling code here:
        MucGiaDienBLL mucGiaDienBLL = new MucGiaDienBLL();

        java.util.Date today = new java.util.Date(System.currentTimeMillis());
        java.sql.Date sqlToday = new Date(today.getTime());

        if (tf_QuyDinhGiaDien_TuKW.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống từ KW");
            return;
        }

        if (tf_QuyDinhGiaDien_DenKW.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống đến KW");
            return;
        }

        if (tf_QuyDinhGiaDien_Gia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống giá điện");
            return;
        }
        
        if(!tb_QuyDinhGiaDien.isColumnSelected(0) && !tb_QuyDinhGiaDien.isColumnSelected(1) && !tb_QuyDinhGiaDien.isColumnSelected(2) && !tb_QuyDinhGiaDien.isColumnSelected(3)
                && !tb_QuyDinhGiaDien.isColumnSelected(4))
        {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn mã giá điện ở bảng phía dưới sau đó nhập thông tin cập nhật vào khung ở trên.");
            return;
        }

        int index = tb_QuyDinhGiaDien.getSelectedRow();
        MucGiaDienEntity mucGiaDienEntity = new MucGiaDienEntity();
        mucGiaDienEntity.setMaGiaDien((int) tb_QuyDinhGiaDien.getValueAt(index, 0));
        mucGiaDienEntity.setNgayApDung(sqlToday);
        mucGiaDienEntity.setTuKW(Float.parseFloat(tf_QuyDinhGiaDien_TuKW.getText().trim()));
        mucGiaDienEntity.setDenKW(Float.parseFloat(tf_QuyDinhGiaDien_DenKW.getText().trim()));
        mucGiaDienEntity.setGiaDien(tf_QuyDinhGiaDien_Gia.getText().trim());


        mucGiaDienBLL.Update(mucGiaDienEntity.getMaGiaDien(), mucGiaDienEntity.getNgayApDung(), mucGiaDienEntity.getTuKW(), mucGiaDienEntity.getDenKW(), mucGiaDienEntity.getGiaDien());
        JOptionPane.showMessageDialog(this, "Cập nhật thành công");
        ShowTable();

    }//GEN-LAST:event_btn_QuyDinhGiaDien_LuuActionPerformed

    private void btn_QuyDinhGiaDien_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuyDinhGiaDien_huyActionPerformed
        // TODO add your handling code here:
        tf_QuyDinhGiaDien_DenKW.setText("");
        tf_QuyDinhGiaDien_TuKW.setText("");
        tf_QuyDinhGiaDien_Gia.setText("");
    }//GEN-LAST:event_btn_QuyDinhGiaDien_huyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuyDinhGiaDienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuyDinhGiaDienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuyDinhGiaDienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuyDinhGiaDienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuyDinhGiaDienFrame().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_QuyDinhGiaDien_Luu;
  private javax.swing.JButton btn_QuyDinhGiaDien_huy;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lb_QuyDinhGiaDien_DenKW;
  private javax.swing.JLabel lb_QuyDinhGiaDien_Gia;
  private javax.swing.JLabel lb_QuyDinhGiaDien_GiaDien;
  private javax.swing.JLabel lb_QuyDinhGiaDien_TuKW;
  private javax.swing.JPanel pn_QuyDinhGiaDien;
  private javax.swing.JPanel pn_QuyDinhGiaDien_ThongTin;
  private javax.swing.JTable tb_QuyDinhGiaDien;
  private javax.swing.JTextField tf_QuyDinhGiaDien_DenKW;
  private javax.swing.JTextField tf_QuyDinhGiaDien_Gia;
  private javax.swing.JTextField tf_QuyDinhGiaDien_TuKW;
  // End of variables declaration//GEN-END:variables
}
