/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan;

import BLL.TinhBLL;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

public class TinhFrame extends javax.swing.JFrame {

    /**
     * Creates new form TinhFrame
     */
    public TinhFrame() {
        initComponents();
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_Tinh = new javax.swing.JPanel();
        lb_Tinh = new javax.swing.JLabel();
        pn_ThongTinTinh = new javax.swing.JPanel();
        lb_Tinh_Tinh = new javax.swing.JLabel();
        tf_Tinh = new javax.swing.JTextField();
        btn_Tinh_Them = new javax.swing.JButton();
        btn_Tinh_Xoa = new javax.swing.JButton();
        btn_Tinh_Sua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Tinh = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pn_Tinh.setBackground(new java.awt.Color(255, 255, 255));
        pn_Tinh.setForeground(new java.awt.Color(240, 240, 240));

        lb_Tinh.setBackground(new java.awt.Color(255, 255, 255));
        lb_Tinh.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_Tinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Tinh.setText("TỈNH - THÀNH PHỐ");
        lb_Tinh.setOpaque(true);

        pn_ThongTinTinh.setBackground(new java.awt.Color(255, 255, 255));
        pn_ThongTinTinh.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tỉnh"));

        lb_Tinh_Tinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_Tinh_Tinh.setText("Tỉnh:");

        javax.swing.GroupLayout pn_ThongTinTinhLayout = new javax.swing.GroupLayout(pn_ThongTinTinh);
        pn_ThongTinTinh.setLayout(pn_ThongTinTinhLayout);
        pn_ThongTinTinhLayout.setHorizontalGroup(
            pn_ThongTinTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ThongTinTinhLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lb_Tinh_Tinh, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(tf_Tinh, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        pn_ThongTinTinhLayout.setVerticalGroup(
            pn_ThongTinTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ThongTinTinhLayout.createSequentialGroup()
                .addGroup(pn_ThongTinTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Tinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_Tinh_Tinh))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        btn_Tinh_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checked.png"))); // NOI18N
        btn_Tinh_Them.setText("Thêm");
        btn_Tinh_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Tinh_ThemActionPerformed(evt);
            }
        });

        btn_Tinh_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/unchecked.png"))); // NOI18N
        btn_Tinh_Xoa.setText("Xóa");
        btn_Tinh_Xoa.setToolTipText("");
        btn_Tinh_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Tinh_XoaActionPerformed(evt);
            }
        });

        btn_Tinh_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Refresh-icon.png"))); // NOI18N
        btn_Tinh_Sua.setText("Sửa");
        btn_Tinh_Sua.setToolTipText("");
        btn_Tinh_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Tinh_SuaActionPerformed(evt);
            }
        });

        tb_Tinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Tỉnh", "Tên Tỉnh"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_Tinh.getTableHeader().setReorderingAllowed(false);
        tb_Tinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_TinhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Tinh);

        javax.swing.GroupLayout pn_TinhLayout = new javax.swing.GroupLayout(pn_Tinh);
        pn_Tinh.setLayout(pn_TinhLayout);
        pn_TinhLayout.setHorizontalGroup(
            pn_TinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_TinhLayout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addComponent(btn_Tinh_Them)
                .addGap(18, 18, 18)
                .addComponent(btn_Tinh_Xoa)
                .addGap(18, 18, 18)
                .addComponent(btn_Tinh_Sua)
                .addGap(18, 18, 18))
            .addGroup(pn_TinhLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(pn_ThongTinTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lb_Tinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pn_TinhLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_Tinh_Sua, btn_Tinh_Them, btn_Tinh_Xoa});

        pn_TinhLayout.setVerticalGroup(
            pn_TinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_Tinh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_ThongTinTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(pn_TinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Tinh_Them)
                    .addComponent(btn_Tinh_Xoa)
                    .addComponent(btn_Tinh_Sua))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pn_TinhLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_Tinh_Sua, btn_Tinh_Them, btn_Tinh_Xoa});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_Tinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_Tinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_TinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_TinhMouseClicked
        // TODO add your handling code here:

        int index = tb_Tinh.getSelectedRow();
        tf_Tinh.setText((String) tb_Tinh.getValueAt(index, 1));
    }//GEN-LAST:event_tb_TinhMouseClicked

    private void btn_Tinh_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Tinh_ThemActionPerformed
        // TODO add your handling code here:

        String tenTinh = tf_Tinh.getText().trim();
        TinhBLL tinhBLL = new TinhBLL();

        if (tf_Tinh.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên tỉnh/thành phố muốn thêm.\nSau đó bấm nút thêm");
            return;
        }
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm tỉnh/thành phố " + tenTinh + " vào danh sách?");
        if (choice == JOptionPane.YES_OPTION) {
            if (tinhBLL.TimTenTinh(tenTinh)) {
                JOptionPane.showMessageDialog(this, "Không thể thêm.\nTỉnh/Thành phố này đã có trong danh sách.");
                return;
            }
            tinhBLL.Insert(tenTinh);
            showTable();
            JOptionPane.showMessageDialog(this, "Thêm thành công " + tenTinh + " vào danh sách");
        }
    }//GEN-LAST:event_btn_Tinh_ThemActionPerformed

    private void btn_Tinh_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Tinh_XoaActionPerformed
        // TODO add your handling code here:

        TinhBLL tinhBLL = new TinhBLL();
        String tenTinh = tf_Tinh.getText().trim();
        if (tf_Tinh.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên tỉnh hoặc chọn tỉnh ở bảng phía dưới.");
            return;
        }
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa tỉnh/thành phố " + tenTinh + " khỏi danh sách?");
        if (choice == JOptionPane.YES_OPTION) {
            if (tinhBLL.TimTenTinh(tenTinh) == false) {
                JOptionPane.showMessageDialog(this, "Không thế xóa.\nTỉnh/Thành phố này không có trong danh sách.");
                return;
            }

            if (tinhBLL.KiemTraXoaTinh(tenTinh)) {
                JOptionPane.showMessageDialog(this, "Không thể xóa.\n Có sinh viên đến từ tỉnh này.");
                return;
            }
            tinhBLL.Delete(tenTinh);
            showTable();
            JOptionPane.showMessageDialog(this, "Xóa thành công " + tenTinh + " khỏi danh sách");
        }


    }//GEN-LAST:event_btn_Tinh_XoaActionPerformed

    private void btn_Tinh_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Tinh_SuaActionPerformed
        // TODO add your handling code here:
        TinhBLL tinhBLL = new TinhBLL();
        String tenTinh = tf_Tinh.getText().trim();
        if (!tb_Tinh.isColumnSelected(0) && !tb_Tinh.isColumnSelected(1)) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Tỉnh ở bảng phía dưới.\nSau đó cập nhật lại tên mới ở trên.");
            return;
        }

        int index = tb_Tinh.getSelectedRow();
        int maTinh = (int) tb_Tinh.getValueAt(index, 0);

        if (tf_Tinh.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn tỉnh ở bảng phía dưới sau đó cập nhật tên mới.");
            return;
        }

        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn cập nhật lại tên tỉnh/thành phố được chọn?");
        if (choice == JOptionPane.YES_OPTION) {
            tinhBLL.Update(tenTinh, maTinh);
            JOptionPane.showMessageDialog(this, "Cập nhật thành công");
            showTable();
        }


    }//GEN-LAST:event_btn_Tinh_SuaActionPerformed

    public void showTable() {
        Vector cols = new Vector();
        Vector data = new Vector();
        TinhBLL tinhBLL = new TinhBLL();

        tinhBLL.ShowTable(cols, data);
        tb_Tinh.setModel(new AbstractTableModel() {
            @Override
            public int getRowCount() {
                return data.size();
            }

            @Override
            public int getColumnCount() {
                return cols.size();
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                Vector rowData = (Vector) (data.elementAt(rowIndex));
                return rowData.elementAt(columnIndex);
            }

            @Override
            public String getColumnName(int column) {
                return (String) cols.elementAt(column);
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TinhFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TinhFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TinhFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TinhFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TinhFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Tinh_Sua;
    private javax.swing.JButton btn_Tinh_Them;
    private javax.swing.JButton btn_Tinh_Xoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_Tinh;
    private javax.swing.JLabel lb_Tinh_Tinh;
    private javax.swing.JPanel pn_ThongTinTinh;
    private javax.swing.JPanel pn_Tinh;
    private javax.swing.JTable tb_Tinh;
    private javax.swing.JTextField tf_Tinh;
    // End of variables declaration//GEN-END:variables
}
