/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan;

import BLL.MucGiaDienBLL;
import BLL.TinhBLL;
import BLL.TruongBLL;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;


public class TruongFrame extends javax.swing.JFrame {

    /**
     * Creates new form TruongFrame
     */
    public TruongFrame() {
        initComponents();
        ShowTable();
    }

    public void ShowTable() {
        Vector cols = new Vector();
        Vector data = new Vector();
        TruongBLL truongBLL = new TruongBLL();

        truongBLL.ShowTable(cols, data);
        tb_Truong.setModel(new AbstractTableModel() {
            @Override
            public int getRowCount() {
                return data.size();
            }

            @Override
            public int getColumnCount() {
                return cols.size();
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                Vector rowData = (Vector) (data.elementAt(rowIndex));
                return rowData.elementAt(columnIndex);
            }

            @Override
            public String getColumnName(int column) {
                return (String) cols.elementAt(column);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pn_Truong = new javax.swing.JPanel();
    lb_Truong = new javax.swing.JLabel();
    pn_Truong_ThongTin = new javax.swing.JPanel();
    lb_TenTruong = new javax.swing.JLabel();
    tf_TenTruong = new javax.swing.JTextField();
    lb_MaTruong = new javax.swing.JLabel();
    tf_MaTruong = new javax.swing.JTextField();
    btn_Them = new javax.swing.JButton();
    btn_Xoa = new javax.swing.JButton();
    btn_Sua = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tb_Truong = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setResizable(false);

    pn_Truong.setBackground(new java.awt.Color(255, 255, 255));

    lb_Truong.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    lb_Truong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/school.png"))); // NOI18N
    lb_Truong.setText("TRƯỜNG");

    pn_Truong_ThongTin.setBackground(new java.awt.Color(255, 255, 255));
    pn_Truong_ThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Trường"));

    lb_TenTruong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    lb_TenTruong.setText("Tên Trường:");

    lb_MaTruong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    lb_MaTruong.setText("Mã Trường:");

    javax.swing.GroupLayout pn_Truong_ThongTinLayout = new javax.swing.GroupLayout(pn_Truong_ThongTin);
    pn_Truong_ThongTin.setLayout(pn_Truong_ThongTinLayout);
    pn_Truong_ThongTinLayout.setHorizontalGroup(
      pn_Truong_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pn_Truong_ThongTinLayout.createSequentialGroup()
        .addGap(28, 28, 28)
        .addGroup(pn_Truong_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lb_TenTruong)
          .addComponent(lb_MaTruong))
        .addGap(29, 29, 29)
        .addGroup(pn_Truong_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(tf_TenTruong)
          .addComponent(tf_MaTruong, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
        .addContainerGap())
    );
    pn_Truong_ThongTinLayout.setVerticalGroup(
      pn_Truong_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Truong_ThongTinLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pn_Truong_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lb_MaTruong)
          .addComponent(tf_MaTruong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
        .addGroup(pn_Truong_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(tf_TenTruong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lb_TenTruong))
        .addGap(26, 26, 26))
    );

    btn_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checked.png"))); // NOI18N
    btn_Them.setText("Thêm");
    btn_Them.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_ThemActionPerformed(evt);
      }
    });

    btn_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/unchecked.png"))); // NOI18N
    btn_Xoa.setText("Xóa");
    btn_Xoa.setToolTipText("");
    btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_XoaActionPerformed(evt);
      }
    });

    btn_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Refresh-icon.png"))); // NOI18N
    btn_Sua.setText("Sửa");
    btn_Sua.setToolTipText("");
    btn_Sua.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_SuaActionPerformed(evt);
      }
    });

    tb_Truong.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    tb_Truong.getTableHeader().setReorderingAllowed(false);
    tb_Truong.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tb_TruongMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tb_Truong);

    javax.swing.GroupLayout pn_TruongLayout = new javax.swing.GroupLayout(pn_Truong);
    pn_Truong.setLayout(pn_TruongLayout);
    pn_TruongLayout.setHorizontalGroup(
      pn_TruongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pn_TruongLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btn_Them)
        .addGap(18, 18, 18)
        .addComponent(btn_Xoa)
        .addGap(26, 26, 26)
        .addComponent(btn_Sua)
        .addContainerGap())
      .addGroup(pn_TruongLayout.createSequentialGroup()
        .addGap(262, 262, 262)
        .addComponent(lb_Truong)
        .addGap(0, 0, Short.MAX_VALUE))
      .addGroup(pn_TruongLayout.createSequentialGroup()
        .addGap(95, 95, 95)
        .addComponent(pn_Truong_ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(104, Short.MAX_VALUE))
      .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
    );

    pn_TruongLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_Sua, btn_Them, btn_Xoa});

    pn_TruongLayout.setVerticalGroup(
      pn_TruongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pn_TruongLayout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addComponent(lb_Truong)
        .addGap(18, 18, 18)
        .addComponent(pn_Truong_ThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pn_TruongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btn_Them)
          .addComponent(btn_Xoa)
          .addComponent(btn_Sua))
        .addGap(18, 18, 18)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pn_TruongLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_Sua, btn_Them, btn_Xoa});

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pn_Truong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pn_Truong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void tb_TruongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_TruongMouseClicked
        // TODO add your handling code here:

        int index = tb_Truong.getSelectedRow();
        tf_MaTruong.setText((String) tb_Truong.getValueAt(index, 0));
        tf_TenTruong.setText((String) tb_Truong.getValueAt(index, 1));

    }//GEN-LAST:event_tb_TruongMouseClicked

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        TruongBLL truongBLL = new TruongBLL();

        String tenTruong = tf_TenTruong.getText().trim();
        String maTruong = tf_MaTruong.getText().trim();

        if (tf_TenTruong.getText().trim().equals("") || tf_MaTruong.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ tên và mã trường muốn thêm.\nSau đó bấm nút thêm");
            return;
        }
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm trường " + tenTruong + " vào danh sách?");
        if (choice == JOptionPane.YES_OPTION) {
            if (truongBLL.TimTruong(tenTruong, maTruong)) {
                JOptionPane.showMessageDialog(this, "Không thể thêm.\n Tên Trường hoặc Mã Trường đã có trong danh sách.");
                return;
            }
            truongBLL.Insert(maTruong, tenTruong);
            ShowTable();
            JOptionPane.showMessageDialog(this, "Thêm thành công " + tenTruong + " vào danh sách");
        }
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:

        TruongBLL truongBLL = new TruongBLL();
        String tenTruong = tf_TenTruong.getText().trim();
        String maTruong = tf_MaTruong.getText().trim();
        if (tf_TenTruong.getText().trim().equals("") || tf_MaTruong.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên trường và mã trường hoặc chọn  ở bảng phía dưới.");
            return;
        }
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa trường " + tenTruong + " khỏi danh sách?");
        if (choice == JOptionPane.YES_OPTION) {
            if (truongBLL.TimTruong(tenTruong, maTruong) == false) {
                JOptionPane.showMessageDialog(this, "Không thế xóa.\nTrường này không có trong danh sách.");
                return;
            }
            if (truongBLL.KiemTraXoaTruong(maTruong)) {
                JOptionPane.showMessageDialog(this, "Không thể xóa.\n Có sinh viên đang học trường này.");
                return;
            }
            truongBLL.Delete(maTruong);
            ShowTable();
            JOptionPane.showMessageDialog(this, "Xóa thành công " + tenTruong + " khỏi danh sách");
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:

        String tenTruong = tf_TenTruong.getText().trim();
        String maTruong = tf_MaTruong.getText().trim();

        if (tf_TenTruong.getText().trim().equals("") || tf_MaTruong.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên trường và mã trường hoặc chọn  ở bảng phía dưới.");
            return;
        }
        
        TruongBLL truongBLL = new TruongBLL();
        if (truongBLL.TimTruong(tenTruong, maTruong) == false) {
            JOptionPane.showMessageDialog(this, "Chỉ được phép sửa Tên Trường.\nVui lòng chọn trường ở bảng phía dưới và cập nhật tên mới ở trên");
            return;
        }

        truongBLL.Update(maTruong, tenTruong);
        JOptionPane.showMessageDialog(this, "Cập nhật thành công");
        ShowTable();

    }//GEN-LAST:event_btn_SuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TruongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TruongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TruongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TruongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TruongFrame().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_Sua;
  private javax.swing.JButton btn_Them;
  private javax.swing.JButton btn_Xoa;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lb_MaTruong;
  private javax.swing.JLabel lb_TenTruong;
  private javax.swing.JLabel lb_Truong;
  private javax.swing.JPanel pn_Truong;
  private javax.swing.JPanel pn_Truong_ThongTin;
  private javax.swing.JTable tb_Truong;
  private javax.swing.JTextField tf_MaTruong;
  private javax.swing.JTextField tf_TenTruong;
  // End of variables declaration//GEN-END:variables
}
